// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

// Styling libraries own their object-valued theme. Use colorScheme for the picker.
function RecipePicker({ theme, ...props }: Omit<React.ComponentProps<typeof EmojiPicker>, 'theme'> & { theme?: unknown }) {
  void theme;
  return <EmojiPicker {...props} />;
}

const meta = {
  title: 'Recipes/Examples/GitHub reactions',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="gh-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(RecipePicker)`
  --epr-reactions-bg-color: #ffffff;
  --epr-bg-color: #ffffff;
  --epr-picker-border-color: #d0d7de;
  --epr-hover-bg-color: #eff2f5;
  --epr-hover-bg-color-reduced-opacity: #eff2f5;
  --epr-picker-border-radius: 6px;
  box-shadow: 0 8px 24px rgb(140 149 159 / 20%);

  &[data-epr-part='root'] {
    backdrop-filter: none;
  }

  & [data-epr-part='reactions'] {
    padding: 0 4px;
  }

  & [data-epr-part='reaction'] {
    border-radius: 6px;
  }

  & [data-epr-part='reaction']:focus-visible {
    outline: 2px solid #0969da;
    outline-offset: -2px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(RecipePicker)`
  --epr-reactions-bg-color: #ffffff;
  --epr-bg-color: #ffffff;
  --epr-picker-border-color: #d0d7de;
  --epr-hover-bg-color: #eff2f5;
  --epr-hover-bg-color-reduced-opacity: #eff2f5;
  --epr-picker-border-radius: 6px;
  box-shadow: 0 8px 24px rgb(140 149 159 / 20%);

  &[data-epr-part='root'] {
    backdrop-filter: none;
  }

  & [data-epr-part='reactions'] {
    padding: 0 4px;
  }

  & [data-epr-part='reaction'] {
    border-radius: 6px;
  }

  & [data-epr-part='reaction']:focus-visible {
    outline: 2px solid #0969da;
    outline-offset: -2px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(RecipePicker)({
  "--epr-reactions-bg-color": "#ffffff",
  "--epr-bg-color": "#ffffff",
  "--epr-picker-border-color": "#d0d7de",
  "--epr-hover-bg-color": "#eff2f5",
  "--epr-hover-bg-color-reduced-opacity": "#eff2f5",
  "--epr-picker-border-radius": "6px",
  boxShadow: "0 8px 24px rgb(140 149 159 / 20%)",
  "&[data-epr-part='root']": {
    backdropFilter: "none",
  },
  "& [data-epr-part='reactions']": {
    padding: "0 4px",
  },
  "& [data-epr-part='reaction']": {
    borderRadius: "6px",
  },
  "& [data-epr-part='reaction']:focus-visible": {
    outline: "2px solid #0969da",
    outlineOffset: "-2px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof RecipePicker>) => (
  <RecipePicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-bg-color:#ffffff]',
  '[--epr-picker-border-color:#d0d7de]',
  '[--epr-hover-bg-color:#eff2f5]',
  '[--epr-hover-bg-color-reduced-opacity:#eff2f5]',
  '[--epr-picker-border-radius:6px]',
  '[box-shadow:0_8px_24px_rgb(140_149_159_/_20%)]',
  '[&[data-epr-part=root]]:[backdrop-filter:none]',
  '[&_[data-epr-part=reactions]]:[padding:0_4px]',
  '[&_[data-epr-part=reaction]]:[border-radius:6px]',
  '[&_[data-epr-part=reaction]:focus-visible]:[outline:2px_solid_#0969da]',
  '[&_[data-epr-part=reaction]:focus-visible]:[outline-offset:-2px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--border": "#d0d7de",
  "--accent": "#eff2f5"
} as React.CSSProperties;

const shadcn = [
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-bg-color:var(--popover)]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-hover-bg-color-reduced-opacity:#eff2f5]',
  '[--epr-picker-border-radius:6px]',
  '[box-shadow:0_8px_24px_rgb(140_149_159_/_20%)]',
  '[&[data-epr-part=root]]:[backdrop-filter:none]',
  '[&_[data-epr-part=reactions]]:[padding:0_4px]',
  '[&_[data-epr-part=reaction]]:[border-radius:6px]',
  '[&_[data-epr-part=reaction]:focus-visible]:[outline:2px_solid_#0969da]',
  '[&_[data-epr-part=reaction]:focus-visible]:[outline-offset:-2px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
