// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Intercom rating',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="intercom-scale" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(EmojiPicker)`
  --epr-reactions-bg-color: #f4f6fb;
  --epr-picker-border-color: transparent;
  --epr-hover-bg-color: #e4e9f7;
  --epr-hover-bg-color-reduced-opacity: #e4e9f7;
  --epr-emoji-size: 32px;
  margin: 0 auto;

  &[data-epr-part='root'] {
    width: 100%;
    height: 60px;
    border-radius: 14px;
    backdrop-filter: none;
  }

  & [data-epr-part='reactions'] {
    justify-content: space-around;
    width: 100%;
  }

  & [data-epr-part='reaction'] {
    border-radius: 12px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(EmojiPicker)`
  --epr-reactions-bg-color: #f4f6fb;
  --epr-picker-border-color: transparent;
  --epr-hover-bg-color: #e4e9f7;
  --epr-hover-bg-color-reduced-opacity: #e4e9f7;
  --epr-emoji-size: 32px;
  margin: 0 auto;

  &[data-epr-part='root'] {
    width: 100%;
    height: 60px;
    border-radius: 14px;
    backdrop-filter: none;
  }

  & [data-epr-part='reactions'] {
    justify-content: space-around;
    width: 100%;
  }

  & [data-epr-part='reaction'] {
    border-radius: 12px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(EmojiPicker)({
  "--epr-reactions-bg-color": "#f4f6fb",
  "--epr-picker-border-color": "transparent",
  "--epr-hover-bg-color": "#e4e9f7",
  "--epr-hover-bg-color-reduced-opacity": "#e4e9f7",
  "--epr-emoji-size": "32px",
  margin: "0 auto",
  "&[data-epr-part='root']": {
    width: "100%",
    height: "60px",
    borderRadius: "14px",
    backdropFilter: "none",
  },
  "& [data-epr-part='reactions']": {
    justifyContent: "space-around",
    width: "100%",
  },
  "& [data-epr-part='reaction']": {
    borderRadius: "12px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof EmojiPicker>) => (
  <EmojiPicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-reactions-bg-color:#f4f6fb]',
  '[--epr-picker-border-color:transparent]',
  '[--epr-hover-bg-color:#e4e9f7]',
  '[--epr-hover-bg-color-reduced-opacity:#e4e9f7]',
  '[--epr-emoji-size:32px]',
  '[margin:0_auto]',
  '[&[data-epr-part=root]]:[width:100%]',
  '[&[data-epr-part=root]]:[height:60px]',
  '[&[data-epr-part=root]]:[border-radius:14px]',
  '[&[data-epr-part=root]]:[backdrop-filter:none]',
  '[&_[data-epr-part=reactions]]:[justify-content:space-around]',
  '[&_[data-epr-part=reactions]]:[width:100%]',
  '[&_[data-epr-part=reaction]]:[border-radius:12px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--border": "transparent",
  "--accent": "#e4e9f7"
} as React.CSSProperties;

const shadcn = [
  '[--epr-reactions-bg-color:#f4f6fb]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-hover-bg-color-reduced-opacity:#e4e9f7]',
  '[--epr-emoji-size:32px]',
  '[margin:0_auto]',
  '[&[data-epr-part=root]]:[width:100%]',
  '[&[data-epr-part=root]]:[height:60px]',
  '[&[data-epr-part=root]]:[border-radius:14px]',
  '[&[data-epr-part=root]]:[backdrop-filter:none]',
  '[&_[data-epr-part=reactions]]:[justify-content:space-around]',
  '[&_[data-epr-part=reactions]]:[width:100%]',
  '[&_[data-epr-part=reaction]]:[border-radius:12px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
