// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Teams (Fluent 2)',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="teams-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --fluent-brand: #5b5fc7;
  --epr-bg-color: #ffffff;
  --epr-text-color: #242424;
  --epr-highlight-color: var(--fluent-brand);
  --epr-hover-bg-color: #f5f5f5;
  --epr-focus-bg-color: #ebebeb;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #d1d1d1;
  --epr-search-border-color-active: var(--fluent-brand);
  --epr-search-input-height: 32px;
  --epr-search-input-border-radius: 4px;
  --epr-search-input-padding: 0 10px 0 32px;
  --epr-search-input-text-color: #242424;
  --epr-search-input-placeholder-color: #707070;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #424242;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: var(--fluent-brand);
  --epr-category-icon-inactive-color: #616161;
  --epr-category-navigation-button-size: 20px;
  --epr-preview-height: 44px;
  --epr-preview-emoji-size: 24px;
  --epr-preview-text-color: #242424;
  --epr-preview-border-color: #e0e0e0;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 4px;
  --epr-horizontal-padding: 12px;
  width: 352px;
  height: 400px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  background: #fff;
  box-shadow: 0 0 2px rgb(0 0 0 / 12%), 0 8px 16px rgb(0 0 0 / 14%);
  font-family: 'Segoe UI', 'Segoe UI Web', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #e0e0e0;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 10px 12px 9px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 11px 0 -8px var(--fluent-brand);
  }

  & [data-epr-part='search'] > * {
    padding: 10px 12px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='preview'] {
    font-size: 12px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --fluent-brand: #5b5fc7;
  --epr-bg-color: #ffffff;
  --epr-text-color: #242424;
  --epr-highlight-color: var(--fluent-brand);
  --epr-hover-bg-color: #f5f5f5;
  --epr-focus-bg-color: #ebebeb;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #d1d1d1;
  --epr-search-border-color-active: var(--fluent-brand);
  --epr-search-input-height: 32px;
  --epr-search-input-border-radius: 4px;
  --epr-search-input-padding: 0 10px 0 32px;
  --epr-search-input-text-color: #242424;
  --epr-search-input-placeholder-color: #707070;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #424242;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: var(--fluent-brand);
  --epr-category-icon-inactive-color: #616161;
  --epr-category-navigation-button-size: 20px;
  --epr-preview-height: 44px;
  --epr-preview-emoji-size: 24px;
  --epr-preview-text-color: #242424;
  --epr-preview-border-color: #e0e0e0;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 4px;
  --epr-horizontal-padding: 12px;
  width: 352px;
  height: 400px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  background: #fff;
  box-shadow: 0 0 2px rgb(0 0 0 / 12%), 0 8px 16px rgb(0 0 0 / 14%);
  font-family: 'Segoe UI', 'Segoe UI Web', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #e0e0e0;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 10px 12px 9px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 11px 0 -8px var(--fluent-brand);
  }

  & [data-epr-part='search'] > * {
    padding: 10px 12px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='preview'] {
    font-size: 12px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--fluent-brand": "#5b5fc7",
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#242424",
  "--epr-highlight-color": "var(--fluent-brand)",
  "--epr-hover-bg-color": "#f5f5f5",
  "--epr-focus-bg-color": "#ebebeb",
  "--epr-search-input-bg-color": "#ffffff",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#d1d1d1",
  "--epr-search-border-color-active": "var(--fluent-brand)",
  "--epr-search-input-height": "32px",
  "--epr-search-input-border-radius": "4px",
  "--epr-search-input-padding": "0 10px 0 32px",
  "--epr-search-input-text-color": "#242424",
  "--epr-search-input-placeholder-color": "#707070",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#424242",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "var(--fluent-brand)",
  "--epr-category-icon-inactive-color": "#616161",
  "--epr-category-navigation-button-size": "20px",
  "--epr-preview-height": "44px",
  "--epr-preview-emoji-size": "24px",
  "--epr-preview-text-color": "#242424",
  "--epr-preview-border-color": "#e0e0e0",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "4px",
  "--epr-horizontal-padding": "12px",
  width: "352px",
  height: "400px",
  border: "1px solid #e0e0e0",
  borderRadius: "8px",
  background: "#fff",
  boxShadow: "0 0 2px rgb(0 0 0 / 12%), 0 8px 16px rgb(0 0 0 / 14%)",
  fontFamily: "'Segoe UI', 'Segoe UI Web', -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
  "& [data-epr-part='category-nav']": {
    borderBottom: "1px solid #e0e0e0",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "10px 12px 9px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    boxShadow: "0 11px 0 -8px var(--fluent-brand)",
  },
  "& [data-epr-part='search'] > *": {
    padding: "10px 12px 4px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "4px",
  },
  "& [data-epr-part='preview']": {
    fontSize: "12px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--fluent-brand:#5b5fc7]',
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#242424]',
  '[--epr-highlight-color:var(--fluent-brand)]',
  '[--epr-hover-bg-color:#f5f5f5]',
  '[--epr-focus-bg-color:#ebebeb]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#d1d1d1]',
  '[--epr-search-border-color-active:var(--fluent-brand)]',
  '[--epr-search-input-height:32px]',
  '[--epr-search-input-border-radius:4px]',
  '[--epr-search-input-padding:0_10px_0_32px]',
  '[--epr-search-input-text-color:#242424]',
  '[--epr-search-input-placeholder-color:#707070]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#424242]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:var(--fluent-brand)]',
  '[--epr-category-icon-inactive-color:#616161]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-preview-height:44px]',
  '[--epr-preview-emoji-size:24px]',
  '[--epr-preview-text-color:#242424]',
  '[--epr-preview-border-color:#e0e0e0]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:4px]',
  '[--epr-horizontal-padding:12px]',
  '[width:352px]',
  '[height:400px]',
  '[border:1px_solid_#e0e0e0]',
  '[border-radius:8px]',
  '[background:#fff]',
  '[box-shadow:0_0_2px_rgb(0_0_0_/_12%),_0_8px_16px_rgb(0_0_0_/_14%)]',
  "[font-family:'Segoe_UI',_'Segoe_UI_Web',_-apple-system,_BlinkMacSystemFont,_Roboto,_sans-serif]",
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#e0e0e0]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:10px_12px_9px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_11px_0_-8px_var(--fluent-brand)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_12px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=preview]]:[font-size:12px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#242424",
  "--accent": "#f5f5f5",
  "--input": "#d1d1d1",
  "--popover-foreground": "#242424"
} as React.CSSProperties;

const shadcn = [
  '[--fluent-brand:#5b5fc7]',
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--fluent-brand)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#ebebeb]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--fluent-brand)]',
  '[--epr-search-input-height:32px]',
  '[--epr-search-input-border-radius:4px]',
  '[--epr-search-input-padding:0_10px_0_32px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#707070]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#424242]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:var(--fluent-brand)]',
  '[--epr-category-icon-inactive-color:#616161]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-preview-height:44px]',
  '[--epr-preview-emoji-size:24px]',
  '[--epr-preview-text-color:#242424]',
  '[--epr-preview-border-color:#e0e0e0]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:4px]',
  '[--epr-horizontal-padding:12px]',
  '[width:352px]',
  '[height:400px]',
  '[border:1px_solid_#e0e0e0]',
  '[border-radius:8px]',
  '[background:#fff]',
  '[box-shadow:0_0_2px_rgb(0_0_0_/_12%),_0_8px_16px_rgb(0_0_0_/_14%)]',
  "[font-family:'Segoe_UI',_'Segoe_UI_Web',_-apple-system,_BlinkMacSystemFont,_Roboto,_sans-serif]",
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#e0e0e0]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:10px_12px_9px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_11px_0_-8px_var(--fluent-brand)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_12px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=preview]]:[font-size:12px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
