// ESLint 9 flat config. Same rule set as the former .eslintrc.js.
import js from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  // Generated by scripts/prepare.ts.
  { ignores: ['src/data/emojis*.ts'] },
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      react.configs.flat.recommended,
      jsxA11y.flatConfigs.recommended,
      tseslint.configs.eslintRecommended,
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { ecmaFeatures: { jsx: true } },
      ecmaVersion: 2018,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      import: importPlugin,
      'react-hooks': reactHooks,
    },
    settings: {
      'import/parsers': { '@typescript-eslint/parser': ['.ts', '.tsx'] },
      'import/resolver': { typescript: true },
      react: { version: 'detect' },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-unused-vars': 'off',
      // TypeScript resolves identifiers (and types such as JSX-only
      // globals); the core rule reports false positives on type names.
      'no-undef': 'off',
      'import/extensions': [2, 'never'],
      'import/first': 2,
      'import/newline-after-import': 1,
      'import/no-duplicates': 2,
      'import/no-self-import': 2,
      'import/no-unresolved': [2],
      'import/no-useless-path-segments': 2,
      'import/order': [
        'warn',
        { alphabetize: { order: 'asc' }, 'newlines-between': 'always' },
      ],
      // ESLint 9 also counts `?.` and `??`; 10 keeps the former
      // strictness (max 8 under ESLint <9 counting).
      complexity: [2, { max: 10 }],
      'max-params': [1, { max: 4 }],
      'no-console': 2,
      'no-else-return': 1,
      'no-implicit-globals': 2,
      'no-lonely-if': 2,
      'no-multi-spaces': 1,
      'no-prototype-builtins': 0,
      'no-trailing-spaces': [2, { ignoreComments: false }],
      'no-unneeded-ternary': 2,
      'no-useless-catch': 2,
      'no-useless-computed-key': 2,
      'no-useless-return': 2,
      'no-var': 2,
      'no-warning-comments': 1,
      'object-shorthand': [2, 'always', { avoidQuotes: true }],
      'prefer-const': 2,
      'react/react-in-jsx-scope': 'off',
    },
  },
);
