// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Rebrand · Phosphor terminal',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="crt-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #030a05;
  --epr-text-color: #7dffa7;
  --epr-highlight-color: #39ff7a;
  --epr-hover-bg-color: #0e3b1c;
  --epr-focus-bg-color: #39ff7a;
  --epr-search-input-bg-color: #030a05;
  --epr-search-input-bg-color-active: #030a05;
  --epr-search-border-color: #1f7a3d;
  --epr-search-border-color-active: #39ff7a;
  --epr-search-input-text-color: #b6ffcb;
  --epr-search-input-placeholder-color: #5fd389;
  --epr-search-input-border-radius: 0;
  --epr-search-input-height: 34px;
  --epr-category-label-bg-color: #030a05f2;
  --epr-category-label-text-color: #7dffa7;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #39ff7a;
  --epr-category-icon-inactive-color: #4fbf74;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-variation-picker-bg-color: #062611;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  position: relative;
  width: 380px;
  height: 450px;
  border-radius: 14px;
  background: radial-gradient(ellipse at center, #062611 0%, #030a05 75%);
  box-shadow: inset 0 0 40px rgb(57 255 122 / 18%);
  font-family: 'DejaVu Sans Mono', Menlo, Consolas, monospace;
  text-shadow: 0 0 6px rgb(57 255 122 / 45%);

  &::after {
    content: '';
    position: absolute;
    inset: 0;
    z-index: 10;
    pointer-events: none;
    background: repeating-linear-gradient(0deg, rgb(0 0 0 / 22%) 0 1px, transparent 1px 3px);
  }

  & [data-epr-part='search'] > * {
    padding: 10px 12px 4px;
  }

  & [data-epr-part='search'] input {
    font-family: inherit;
  }

  & .crt-prompt {
    margin: 0;
    font-size: 13px;
    font-weight: 400;
    letter-spacing: 0.04em;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 0;
  }

  & [data-epr-part='emoji']:focus {
    outline: 1px solid #39ff7a;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    outline: 1px solid #39ff7a;
    outline-offset: 3px;
  }

  & [data-epr-part='empty'] {
    justify-content: flex-start;
    color: #b6ffcb;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #030a05;
  --epr-text-color: #7dffa7;
  --epr-highlight-color: #39ff7a;
  --epr-hover-bg-color: #0e3b1c;
  --epr-focus-bg-color: #39ff7a;
  --epr-search-input-bg-color: #030a05;
  --epr-search-input-bg-color-active: #030a05;
  --epr-search-border-color: #1f7a3d;
  --epr-search-border-color-active: #39ff7a;
  --epr-search-input-text-color: #b6ffcb;
  --epr-search-input-placeholder-color: #5fd389;
  --epr-search-input-border-radius: 0;
  --epr-search-input-height: 34px;
  --epr-category-label-bg-color: #030a05f2;
  --epr-category-label-text-color: #7dffa7;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #39ff7a;
  --epr-category-icon-inactive-color: #4fbf74;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-variation-picker-bg-color: #062611;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  position: relative;
  width: 380px;
  height: 450px;
  border-radius: 14px;
  background: radial-gradient(ellipse at center, #062611 0%, #030a05 75%);
  box-shadow: inset 0 0 40px rgb(57 255 122 / 18%);
  font-family: 'DejaVu Sans Mono', Menlo, Consolas, monospace;
  text-shadow: 0 0 6px rgb(57 255 122 / 45%);

  &::after {
    content: '';
    position: absolute;
    inset: 0;
    z-index: 10;
    pointer-events: none;
    background: repeating-linear-gradient(0deg, rgb(0 0 0 / 22%) 0 1px, transparent 1px 3px);
  }

  & [data-epr-part='search'] > * {
    padding: 10px 12px 4px;
  }

  & [data-epr-part='search'] input {
    font-family: inherit;
  }

  & .crt-prompt {
    margin: 0;
    font-size: 13px;
    font-weight: 400;
    letter-spacing: 0.04em;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 0;
  }

  & [data-epr-part='emoji']:focus {
    outline: 1px solid #39ff7a;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    outline: 1px solid #39ff7a;
    outline-offset: 3px;
  }

  & [data-epr-part='empty'] {
    justify-content: flex-start;
    color: #b6ffcb;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#030a05",
  "--epr-text-color": "#7dffa7",
  "--epr-highlight-color": "#39ff7a",
  "--epr-hover-bg-color": "#0e3b1c",
  "--epr-focus-bg-color": "#39ff7a",
  "--epr-search-input-bg-color": "#030a05",
  "--epr-search-input-bg-color-active": "#030a05",
  "--epr-search-border-color": "#1f7a3d",
  "--epr-search-border-color-active": "#39ff7a",
  "--epr-search-input-text-color": "#b6ffcb",
  "--epr-search-input-placeholder-color": "#5fd389",
  "--epr-search-input-border-radius": "0",
  "--epr-search-input-height": "34px",
  "--epr-category-label-bg-color": "#030a05f2",
  "--epr-category-label-text-color": "#7dffa7",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "#39ff7a",
  "--epr-category-icon-inactive-color": "#4fbf74",
  "--epr-category-navigation-button-size": "20px",
  "--epr-emoji-variation-picker-bg-color": "#062611",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "12px",
  position: "relative",
  width: "380px",
  height: "450px",
  borderRadius: "14px",
  background: "radial-gradient(ellipse at center, #062611 0%, #030a05 75%)",
  boxShadow: "inset 0 0 40px rgb(57 255 122 / 18%)",
  fontFamily: "'DejaVu Sans Mono', Menlo, Consolas, monospace",
  textShadow: "0 0 6px rgb(57 255 122 / 45%)",
  "&::after": {
    content: "''",
    position: "absolute",
    inset: "0",
    zIndex: "10",
    pointerEvents: "none",
    background: "repeating-linear-gradient(0deg, rgb(0 0 0 / 22%) 0 1px, transparent 1px 3px)",
  },
  "& [data-epr-part='search'] > *": {
    padding: "10px 12px 4px",
  },
  "& [data-epr-part='search'] input": {
    fontFamily: "inherit",
  },
  "& .crt-prompt": {
    margin: "0",
    fontSize: "13px",
    fontWeight: "400",
    letterSpacing: "0.04em",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "0",
  },
  "& [data-epr-part='emoji']:focus": {
    outline: "1px solid #39ff7a",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    outline: "1px solid #39ff7a",
    outlineOffset: "3px",
  },
  "& [data-epr-part='empty']": {
    justifyContent: "flex-start",
    color: "#b6ffcb",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#030a05]',
  '[--epr-text-color:#7dffa7]',
  '[--epr-highlight-color:#39ff7a]',
  '[--epr-hover-bg-color:#0e3b1c]',
  '[--epr-focus-bg-color:#39ff7a]',
  '[--epr-search-input-bg-color:#030a05]',
  '[--epr-search-input-bg-color-active:#030a05]',
  '[--epr-search-border-color:#1f7a3d]',
  '[--epr-search-border-color-active:#39ff7a]',
  '[--epr-search-input-text-color:#b6ffcb]',
  '[--epr-search-input-placeholder-color:#5fd389]',
  '[--epr-search-input-border-radius:0]',
  '[--epr-search-input-height:34px]',
  '[--epr-category-label-bg-color:#030a05f2]',
  '[--epr-category-label-text-color:#7dffa7]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#39ff7a]',
  '[--epr-category-icon-inactive-color:#4fbf74]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-variation-picker-bg-color:#062611]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[position:relative]',
  '[width:380px]',
  '[height:450px]',
  '[border-radius:14px]',
  '[background:radial-gradient(ellipse_at_center,_#062611_0%,_#030a05_75%)]',
  '[box-shadow:inset_0_0_40px_rgb(57_255_122_/_18%)]',
  "[font-family:'DejaVu_Sans_Mono',_Menlo,_Consolas,_monospace]",
  '[text-shadow:0_0_6px_rgb(57_255_122_/_45%)]',
  "[&::after]:[content:'']",
  '[&::after]:[position:absolute]',
  '[&::after]:[inset:0]',
  '[&::after]:[z-index:10]',
  '[&::after]:[pointer-events:none]',
  '[&::after]:[background:repeating-linear-gradient(0deg,_rgb(0_0_0_/_22%)_0_1px,_transparent_1px_3px)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_12px_4px]',
  '[&_[data-epr-part=search]_input]:[font-family:inherit]',
  '[&_.crt-prompt]:[margin:0]',
  '[&_.crt-prompt]:[font-size:13px]',
  '[&_.crt-prompt]:[font-weight:400]',
  '[&_.crt-prompt]:[letter-spacing:0.04em]',
  '[&_.crt-prompt]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:0]',
  '[&_[data-epr-part=emoji]:focus]:[outline:1px_solid_#39ff7a]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline:1px_solid_#39ff7a]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline-offset:3px]',
  '[&_[data-epr-part=empty]]:[justify-content:flex-start]',
  '[&_[data-epr-part=empty]]:[color:#b6ffcb]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#030a05",
  "--muted-foreground": "#7dffa7",
  "--primary": "#39ff7a",
  "--accent": "#0e3b1c",
  "--input": "#1f7a3d",
  "--ring": "#39ff7a",
  "--popover-foreground": "#b6ffcb"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#39ff7a]',
  '[--epr-search-input-bg-color:#030a05]',
  '[--epr-search-input-bg-color-active:#030a05]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#5fd389]',
  '[--epr-search-input-border-radius:0]',
  '[--epr-search-input-height:34px]',
  '[--epr-category-label-bg-color:#030a05f2]',
  '[--epr-category-label-text-color:#7dffa7]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#39ff7a]',
  '[--epr-category-icon-inactive-color:#4fbf74]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-variation-picker-bg-color:#062611]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[position:relative]',
  '[width:380px]',
  '[height:450px]',
  '[border-radius:14px]',
  '[background:radial-gradient(ellipse_at_center,_#062611_0%,_#030a05_75%)]',
  '[box-shadow:inset_0_0_40px_rgb(57_255_122_/_18%)]',
  "[font-family:'DejaVu_Sans_Mono',_Menlo,_Consolas,_monospace]",
  '[text-shadow:0_0_6px_rgb(57_255_122_/_45%)]',
  "[&::after]:[content:'']",
  '[&::after]:[position:absolute]',
  '[&::after]:[inset:0]',
  '[&::after]:[z-index:10]',
  '[&::after]:[pointer-events:none]',
  '[&::after]:[background:repeating-linear-gradient(0deg,_rgb(0_0_0_/_22%)_0_1px,_transparent_1px_3px)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_12px_4px]',
  '[&_[data-epr-part=search]_input]:[font-family:inherit]',
  '[&_.crt-prompt]:[margin:0]',
  '[&_.crt-prompt]:[font-size:13px]',
  '[&_.crt-prompt]:[font-weight:400]',
  '[&_.crt-prompt]:[letter-spacing:0.04em]',
  '[&_.crt-prompt]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:0]',
  '[&_[data-epr-part=emoji]:focus]:[outline:1px_solid_#39ff7a]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline:1px_solid_#39ff7a]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline-offset:3px]',
  '[&_[data-epr-part=empty]]:[justify-content:flex-start]',
  '[&_[data-epr-part=empty]]:[color:#b6ffcb]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
