// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Team chat composer',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="chat-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #52525b;
  --epr-highlight-color: #4f46e5;
  --epr-hover-bg-color: #f4f4f5;
  --epr-focus-bg-color: #e0e7ff;
  --epr-picker-border-color: #e4e4e7;
  --epr-search-input-bg-color: #f4f4f5;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #6366f1;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #18181b;
  --epr-search-input-placeholder-color: #71717a;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #52525b;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #4f46e5;
  --epr-category-icon-inactive-color: #71717a;
  --epr-category-navigation-button-size: 20px;
  --epr-preview-height: 46px;
  --epr-preview-emoji-size: 26px;
  --epr-preview-text-color: #18181b;
  --epr-preview-border-color: #e4e4e7;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  width: 340px;
  height: 380px;
  border: 1px solid #e4e4e7;
  border-radius: 12px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 12px 12px 4px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 12px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 10px 0 -8px #4f46e5;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }

  & [data-epr-part='preview'] {
    font-size: 13px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #52525b;
  --epr-highlight-color: #4f46e5;
  --epr-hover-bg-color: #f4f4f5;
  --epr-focus-bg-color: #e0e7ff;
  --epr-picker-border-color: #e4e4e7;
  --epr-search-input-bg-color: #f4f4f5;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #6366f1;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #18181b;
  --epr-search-input-placeholder-color: #71717a;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #52525b;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #4f46e5;
  --epr-category-icon-inactive-color: #71717a;
  --epr-category-navigation-button-size: 20px;
  --epr-preview-height: 46px;
  --epr-preview-emoji-size: 26px;
  --epr-preview-text-color: #18181b;
  --epr-preview-border-color: #e4e4e7;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  width: 340px;
  height: 380px;
  border: 1px solid #e4e4e7;
  border-radius: 12px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 12px 12px 4px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 12px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 10px 0 -8px #4f46e5;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }

  & [data-epr-part='preview'] {
    font-size: 13px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#52525b",
  "--epr-highlight-color": "#4f46e5",
  "--epr-hover-bg-color": "#f4f4f5",
  "--epr-focus-bg-color": "#e0e7ff",
  "--epr-picker-border-color": "#e4e4e7",
  "--epr-search-input-bg-color": "#f4f4f5",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "#6366f1",
  "--epr-search-input-height": "34px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-text-color": "#18181b",
  "--epr-search-input-placeholder-color": "#71717a",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#52525b",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "#4f46e5",
  "--epr-category-icon-inactive-color": "#71717a",
  "--epr-category-navigation-button-size": "20px",
  "--epr-preview-height": "46px",
  "--epr-preview-emoji-size": "26px",
  "--epr-preview-text-color": "#18181b",
  "--epr-preview-border-color": "#e4e4e7",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "12px",
  width: "340px",
  height: "380px",
  border: "1px solid #e4e4e7",
  borderRadius: "12px",
  background: "#ffffff",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "12px 12px 4px",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "8px 12px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    boxShadow: "0 10px 0 -8px #4f46e5",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "8px",
  },
  "& [data-epr-part='preview']": {
    fontSize: "13px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#52525b]',
  '[--epr-highlight-color:#4f46e5]',
  '[--epr-hover-bg-color:#f4f4f5]',
  '[--epr-focus-bg-color:#e0e7ff]',
  '[--epr-picker-border-color:#e4e4e7]',
  '[--epr-search-input-bg-color:#f4f4f5]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:#6366f1]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:#18181b]',
  '[--epr-search-input-placeholder-color:#71717a]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#52525b]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#4f46e5]',
  '[--epr-category-icon-inactive-color:#71717a]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-preview-height:46px]',
  '[--epr-preview-emoji-size:26px]',
  '[--epr-preview-text-color:#18181b]',
  '[--epr-preview-border-color:#e4e4e7]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[width:340px]',
  '[height:380px]',
  '[border:1px_solid_#e4e4e7]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:12px_12px_4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_12px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_10px_0_-8px_#4f46e5]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
  '[&_[data-epr-part=preview]]:[font-size:13px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#52525b",
  "--primary": "#4f46e5",
  "--accent": "#f4f4f5",
  "--border": "#e4e4e7",
  "--input": "transparent",
  "--ring": "#6366f1",
  "--popover-foreground": "#18181b"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e0e7ff]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-search-input-bg-color:#f4f4f5]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#71717a]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#52525b]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#4f46e5]',
  '[--epr-category-icon-inactive-color:#71717a]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-preview-height:46px]',
  '[--epr-preview-emoji-size:26px]',
  '[--epr-preview-text-color:#18181b]',
  '[--epr-preview-border-color:#e4e4e7]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[width:340px]',
  '[height:380px]',
  '[border:1px_solid_#e4e4e7]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:12px_12px_4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_12px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_10px_0_-8px_#4f46e5]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
  '[&_[data-epr-part=preview]]:[font-size:13px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
