// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Project icon picker',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="project-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #d97706;
  --epr-hover-bg-color: #fef3c7;
  --epr-focus-bg-color: #fde68a;
  --epr-search-input-bg-color: #f9fafb;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #d1d5db;
  --epr-search-border-color-active: #d97706;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #111827;
  --epr-search-input-placeholder-color: #6b7280;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #4b5563;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #b45309;
  --epr-category-icon-inactive-color: #6b7280;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 10px;
  height: 260px;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & .project-toolbar {
    display: flex;
    align-items: center;
    border-bottom: 1px solid #f3f4f6;
  }

  & [data-epr-part='search'] {
    flex: 1;
  }

  & [data-epr-part='search'] > * {
    padding: 10px 6px 10px 10px;
  }

  & [data-epr-part='category-nav'] > * {
    gap: 6px;
    padding: 0 10px 0 4px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #fef3c7;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 10px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #d97706;
  --epr-hover-bg-color: #fef3c7;
  --epr-focus-bg-color: #fde68a;
  --epr-search-input-bg-color: #f9fafb;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #d1d5db;
  --epr-search-border-color-active: #d97706;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #111827;
  --epr-search-input-placeholder-color: #6b7280;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #4b5563;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #b45309;
  --epr-category-icon-inactive-color: #6b7280;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 10px;
  height: 260px;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & .project-toolbar {
    display: flex;
    align-items: center;
    border-bottom: 1px solid #f3f4f6;
  }

  & [data-epr-part='search'] {
    flex: 1;
  }

  & [data-epr-part='search'] > * {
    padding: 10px 6px 10px 10px;
  }

  & [data-epr-part='category-nav'] > * {
    gap: 6px;
    padding: 0 10px 0 4px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #fef3c7;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 10px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#4b5563",
  "--epr-highlight-color": "#d97706",
  "--epr-hover-bg-color": "#fef3c7",
  "--epr-focus-bg-color": "#fde68a",
  "--epr-search-input-bg-color": "#f9fafb",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#d1d5db",
  "--epr-search-border-color-active": "#d97706",
  "--epr-search-input-height": "34px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-text-color": "#111827",
  "--epr-search-input-placeholder-color": "#6b7280",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#4b5563",
  "--epr-category-label-height": "28px",
  "--epr-category-icon-active-color": "#b45309",
  "--epr-category-icon-inactive-color": "#6b7280",
  "--epr-category-navigation-button-size": "20px",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "10px",
  height: "260px",
  border: "1px solid #e5e7eb",
  borderRadius: "10px",
  background: "#ffffff",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& .project-toolbar": {
    display: "flex",
    alignItems: "center",
    borderBottom: "1px solid #f3f4f6",
  },
  "& [data-epr-part='search']": {
    flex: "1",
  },
  "& [data-epr-part='search'] > *": {
    padding: "10px 6px 10px 10px",
  },
  "& [data-epr-part='category-nav'] > *": {
    gap: "6px",
    padding: "0 10px 0 4px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    borderRadius: "6px",
    backgroundColor: "#fef3c7",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "10px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#4b5563]',
  '[--epr-highlight-color:#d97706]',
  '[--epr-hover-bg-color:#fef3c7]',
  '[--epr-focus-bg-color:#fde68a]',
  '[--epr-search-input-bg-color:#f9fafb]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#d1d5db]',
  '[--epr-search-border-color-active:#d97706]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:#111827]',
  '[--epr-search-input-placeholder-color:#6b7280]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#b45309]',
  '[--epr-category-icon-inactive-color:#6b7280]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:10px]',
  '[height:260px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:10px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_.project-toolbar]:[display:flex]',
  '[&_.project-toolbar]:[align-items:center]',
  '[&_.project-toolbar]:[border-bottom:1px_solid_#f3f4f6]',
  '[&_[data-epr-part=search]]:[flex:1]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_6px_10px_10px]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:6px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:0_10px_0_4px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#fef3c7]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:10px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#4b5563",
  "--primary": "#d97706",
  "--accent": "#fef3c7",
  "--input": "#d1d5db",
  "--ring": "#d97706",
  "--popover-foreground": "#111827"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#fde68a]',
  '[--epr-search-input-bg-color:#f9fafb]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#6b7280]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#b45309]',
  '[--epr-category-icon-inactive-color:#6b7280]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:10px]',
  '[height:260px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:10px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_.project-toolbar]:[display:flex]',
  '[&_.project-toolbar]:[align-items:center]',
  '[&_.project-toolbar]:[border-bottom:1px_solid_#f3f4f6]',
  '[&_[data-epr-part=search]]:[flex:1]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_6px_10px_10px]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:6px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:0_10px_0_4px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#fef3c7]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:10px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
