// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Habit tracker (mobile)',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="habit-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #475569;
  --epr-highlight-color: #0e7490;
  --epr-hover-bg-color: #ecfeff;
  --epr-focus-bg-color: #cffafe;
  --epr-search-input-bg-color: #f1f5f9;
  --epr-search-input-bg-color-active: #f1f5f9;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #0e7490;
  --epr-search-input-height: 38px;
  --epr-search-input-border-radius: 999px;
  --epr-search-input-padding: 0 16px 0 38px;
  --epr-search-input-text-color: #0f172a;
  --epr-search-input-placeholder-color: #64748b;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #475569;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #0e7490;
  --epr-category-icon-inactive-color: #64748b;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 8px;
  --epr-horizontal-padding: 14px;
  flex: 1;
  min-height: 0;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 0 14px 6px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 12px 8px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 999px;
    background-color: #cffafe;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 700;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 14px;
    background-color: #f8fafc;
  }

  & [data-epr-part='emoji']:hover {
    background-color: #ecfeff;
  }

  & [data-epr-part='emoji']:focus {
    background-color: #cffafe;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #475569;
  --epr-highlight-color: #0e7490;
  --epr-hover-bg-color: #ecfeff;
  --epr-focus-bg-color: #cffafe;
  --epr-search-input-bg-color: #f1f5f9;
  --epr-search-input-bg-color-active: #f1f5f9;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #0e7490;
  --epr-search-input-height: 38px;
  --epr-search-input-border-radius: 999px;
  --epr-search-input-padding: 0 16px 0 38px;
  --epr-search-input-text-color: #0f172a;
  --epr-search-input-placeholder-color: #64748b;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #475569;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #0e7490;
  --epr-category-icon-inactive-color: #64748b;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 8px;
  --epr-horizontal-padding: 14px;
  flex: 1;
  min-height: 0;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 0 14px 6px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 12px 8px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 999px;
    background-color: #cffafe;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 700;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 14px;
    background-color: #f8fafc;
  }

  & [data-epr-part='emoji']:hover {
    background-color: #ecfeff;
  }

  & [data-epr-part='emoji']:focus {
    background-color: #cffafe;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#475569",
  "--epr-highlight-color": "#0e7490",
  "--epr-hover-bg-color": "#ecfeff",
  "--epr-focus-bg-color": "#cffafe",
  "--epr-search-input-bg-color": "#f1f5f9",
  "--epr-search-input-bg-color-active": "#f1f5f9",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "#0e7490",
  "--epr-search-input-height": "38px",
  "--epr-search-input-border-radius": "999px",
  "--epr-search-input-padding": "0 16px 0 38px",
  "--epr-search-input-text-color": "#0f172a",
  "--epr-search-input-placeholder-color": "#64748b",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#475569",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "#0e7490",
  "--epr-category-icon-inactive-color": "#64748b",
  "--epr-category-navigation-button-size": "22px",
  "--epr-emoji-size": "30px",
  "--epr-emoji-padding": "8px",
  "--epr-horizontal-padding": "14px",
  flex: "1",
  minHeight: "0",
  background: "#ffffff",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "0 14px 6px",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "6px 12px 8px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    borderRadius: "999px",
    backgroundColor: "#cffafe",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "13px",
    fontWeight: "700",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "14px",
    backgroundColor: "#f8fafc",
  },
  "& [data-epr-part='emoji']:hover": {
    backgroundColor: "#ecfeff",
  },
  "& [data-epr-part='emoji']:focus": {
    backgroundColor: "#cffafe",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#475569]',
  '[--epr-highlight-color:#0e7490]',
  '[--epr-hover-bg-color:#ecfeff]',
  '[--epr-focus-bg-color:#cffafe]',
  '[--epr-search-input-bg-color:#f1f5f9]',
  '[--epr-search-input-bg-color-active:#f1f5f9]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:#0e7490]',
  '[--epr-search-input-height:38px]',
  '[--epr-search-input-border-radius:999px]',
  '[--epr-search-input-padding:0_16px_0_38px]',
  '[--epr-search-input-text-color:#0f172a]',
  '[--epr-search-input-placeholder-color:#64748b]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#475569]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#0e7490]',
  '[--epr-category-icon-inactive-color:#64748b]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:8px]',
  '[--epr-horizontal-padding:14px]',
  '[flex:1]',
  '[min-height:0]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:0_14px_6px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_12px_8px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:999px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#cffafe]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:14px]',
  '[&_[data-epr-part=emoji]]:[background-color:#f8fafc]',
  '[&_[data-epr-part=emoji]:hover]:[background-color:#ecfeff]',
  '[&_[data-epr-part=emoji]:focus]:[background-color:#cffafe]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#475569",
  "--primary": "#0e7490",
  "--accent": "#ecfeff",
  "--input": "transparent",
  "--ring": "#0e7490",
  "--popover-foreground": "#0f172a"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#cffafe]',
  '[--epr-search-input-bg-color:#f1f5f9]',
  '[--epr-search-input-bg-color-active:#f1f5f9]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:38px]',
  '[--epr-search-input-border-radius:999px]',
  '[--epr-search-input-padding:0_16px_0_38px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#64748b]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#475569]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#0e7490]',
  '[--epr-category-icon-inactive-color:#64748b]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:8px]',
  '[--epr-horizontal-padding:14px]',
  '[flex:1]',
  '[min-height:0]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:0_14px_6px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_12px_8px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:999px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#cffafe]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:14px]',
  '[&_[data-epr-part=emoji]]:[background-color:#f8fafc]',
  '[&_[data-epr-part=emoji]:hover]:[background-color:#ecfeff]',
  '[&_[data-epr-part=emoji]:focus]:[background-color:#cffafe]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
