// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/iMessage tapback',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="imessage-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(EmojiPicker)`
  --epr-reactions-bg-color: rgb(58 58 60 / 85%);
  --epr-bg-color: #1c1c1e;
  --epr-picker-border-color: transparent;
  --epr-hover-bg-color: rgb(255 255 255 / 12%);
  --epr-hover-bg-color-reduced-opacity: rgb(255 255 255 / 12%);
  --epr-text-color: #ebebf5;
  --epr-category-label-bg-color: rgb(28 28 30 / 94%);
  --epr-category-label-text-color: #ebebf5;
  --epr-search-input-bg-color: rgb(118 118 128 / 24%);
  --epr-search-input-bg-color-active: rgb(118 118 128 / 32%);
  --epr-search-input-text-color: #ebebf5;
  --epr-search-input-placeholder-color: rgb(235 235 245 / 60%);
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #0a84ff;
  --epr-emoji-size: 34px;
  margin-left: auto;
  box-shadow: 0 10px 30px rgb(0 0 0 / 50%);

  &[data-epr-part='root'] {
    height: 56px;
  }

  & [data-epr-part='reactions'] {
    gap: 2px;
    padding: 0 8px;
  }

  & [data-epr-part='expand-reactions'] {
    background-color: rgb(255 255 255 / 14%);
    filter: invert(1) brightness(1.6);
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(EmojiPicker)`
  --epr-reactions-bg-color: rgb(58 58 60 / 85%);
  --epr-bg-color: #1c1c1e;
  --epr-picker-border-color: transparent;
  --epr-hover-bg-color: rgb(255 255 255 / 12%);
  --epr-hover-bg-color-reduced-opacity: rgb(255 255 255 / 12%);
  --epr-text-color: #ebebf5;
  --epr-category-label-bg-color: rgb(28 28 30 / 94%);
  --epr-category-label-text-color: #ebebf5;
  --epr-search-input-bg-color: rgb(118 118 128 / 24%);
  --epr-search-input-bg-color-active: rgb(118 118 128 / 32%);
  --epr-search-input-text-color: #ebebf5;
  --epr-search-input-placeholder-color: rgb(235 235 245 / 60%);
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #0a84ff;
  --epr-emoji-size: 34px;
  margin-left: auto;
  box-shadow: 0 10px 30px rgb(0 0 0 / 50%);

  &[data-epr-part='root'] {
    height: 56px;
  }

  & [data-epr-part='reactions'] {
    gap: 2px;
    padding: 0 8px;
  }

  & [data-epr-part='expand-reactions'] {
    background-color: rgb(255 255 255 / 14%);
    filter: invert(1) brightness(1.6);
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(EmojiPicker)({
  "--epr-reactions-bg-color": "rgb(58 58 60 / 85%)",
  "--epr-bg-color": "#1c1c1e",
  "--epr-picker-border-color": "transparent",
  "--epr-hover-bg-color": "rgb(255 255 255 / 12%)",
  "--epr-hover-bg-color-reduced-opacity": "rgb(255 255 255 / 12%)",
  "--epr-text-color": "#ebebf5",
  "--epr-category-label-bg-color": "rgb(28 28 30 / 94%)",
  "--epr-category-label-text-color": "#ebebf5",
  "--epr-search-input-bg-color": "rgb(118 118 128 / 24%)",
  "--epr-search-input-bg-color-active": "rgb(118 118 128 / 32%)",
  "--epr-search-input-text-color": "#ebebf5",
  "--epr-search-input-placeholder-color": "rgb(235 235 245 / 60%)",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "#0a84ff",
  "--epr-emoji-size": "34px",
  marginLeft: "auto",
  boxShadow: "0 10px 30px rgb(0 0 0 / 50%)",
  "&[data-epr-part='root']": {
    height: "56px",
  },
  "& [data-epr-part='reactions']": {
    gap: "2px",
    padding: "0 8px",
  },
  "& [data-epr-part='expand-reactions']": {
    backgroundColor: "rgb(255 255 255 / 14%)",
    filter: "invert(1) brightness(1.6)",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof EmojiPicker>) => (
  <EmojiPicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-reactions-bg-color:rgb(58_58_60_/_85%)]',
  '[--epr-bg-color:#1c1c1e]',
  '[--epr-picker-border-color:transparent]',
  '[--epr-hover-bg-color:rgb(255_255_255_/_12%)]',
  '[--epr-hover-bg-color-reduced-opacity:rgb(255_255_255_/_12%)]',
  '[--epr-text-color:#ebebf5]',
  '[--epr-category-label-bg-color:rgb(28_28_30_/_94%)]',
  '[--epr-category-label-text-color:#ebebf5]',
  '[--epr-search-input-bg-color:rgb(118_118_128_/_24%)]',
  '[--epr-search-input-bg-color-active:rgb(118_118_128_/_32%)]',
  '[--epr-search-input-text-color:#ebebf5]',
  '[--epr-search-input-placeholder-color:rgb(235_235_245_/_60%)]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:#0a84ff]',
  '[--epr-emoji-size:34px]',
  '[margin-left:auto]',
  '[box-shadow:0_10px_30px_rgb(0_0_0_/_50%)]',
  '[&[data-epr-part=root]]:[height:56px]',
  '[&_[data-epr-part=reactions]]:[gap:2px]',
  '[&_[data-epr-part=reactions]]:[padding:0_8px]',
  '[&_[data-epr-part=expand-reactions]]:[background-color:rgb(255_255_255_/_14%)]',
  '[&_[data-epr-part=expand-reactions]]:[filter:invert(1)_brightness(1.6)]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#1c1c1e",
  "--border": "transparent",
  "--accent": "rgb(255 255 255 / 12%)",
  "--muted-foreground": "#ebebf5",
  "--popover-foreground": "#ebebf5",
  "--input": "transparent",
  "--ring": "#0a84ff"
} as React.CSSProperties;

const shadcn = [
  '[--epr-reactions-bg-color:rgb(58_58_60_/_85%)]',
  '[--epr-bg-color:var(--popover)]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-hover-bg-color-reduced-opacity:rgb(255_255_255_/_12%)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-category-label-bg-color:rgb(28_28_30_/_94%)]',
  '[--epr-category-label-text-color:#ebebf5]',
  '[--epr-search-input-bg-color:rgb(118_118_128_/_24%)]',
  '[--epr-search-input-bg-color-active:rgb(118_118_128_/_32%)]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:rgb(235_235_245_/_60%)]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-emoji-size:34px]',
  '[margin-left:auto]',
  '[box-shadow:0_10px_30px_rgb(0_0_0_/_50%)]',
  '[&[data-epr-part=root]]:[height:56px]',
  '[&_[data-epr-part=reactions]]:[gap:2px]',
  '[&_[data-epr-part=reactions]]:[padding:0_8px]',
  '[&_[data-epr-part=expand-reactions]]:[background-color:rgb(255_255_255_/_14%)]',
  '[&_[data-epr-part=expand-reactions]]:[filter:invert(1)_brightness(1.6)]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
