// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Set a status dialog',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="status-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #f8fafc;
  --epr-text-color: #475569;
  --epr-highlight-color: #0f172a;
  --epr-hover-bg-color: #e2e8f0;
  --epr-focus-bg-color: #cbd5e1;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #cbd5e1;
  --epr-search-border-color-active: #0f172a;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #0f172a;
  --epr-search-input-placeholder-color: #64748b;
  --epr-category-label-bg-color: #f8fafcf2;
  --epr-category-label-text-color: #475569;
  --epr-category-label-height: 28px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 10px;
  height: 250px;
  margin-top: 12px;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  background: var(--epr-bg-color);

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #f8fafc;
  --epr-text-color: #475569;
  --epr-highlight-color: #0f172a;
  --epr-hover-bg-color: #e2e8f0;
  --epr-focus-bg-color: #cbd5e1;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #cbd5e1;
  --epr-search-border-color-active: #0f172a;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #0f172a;
  --epr-search-input-placeholder-color: #64748b;
  --epr-category-label-bg-color: #f8fafcf2;
  --epr-category-label-text-color: #475569;
  --epr-category-label-height: 28px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 10px;
  height: 250px;
  margin-top: 12px;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  background: var(--epr-bg-color);

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#f8fafc",
  "--epr-text-color": "#475569",
  "--epr-highlight-color": "#0f172a",
  "--epr-hover-bg-color": "#e2e8f0",
  "--epr-focus-bg-color": "#cbd5e1",
  "--epr-search-input-bg-color": "#ffffff",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#cbd5e1",
  "--epr-search-border-color-active": "#0f172a",
  "--epr-search-input-height": "34px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-text-color": "#0f172a",
  "--epr-search-input-placeholder-color": "#64748b",
  "--epr-category-label-bg-color": "#f8fafcf2",
  "--epr-category-label-text-color": "#475569",
  "--epr-category-label-height": "28px",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "10px",
  height: "250px",
  marginTop: "12px",
  border: "1px solid #e2e8f0",
  borderRadius: "10px",
  background: "var(--epr-bg-color)",
  "& [data-epr-part='search'] > *": {
    padding: "10px 10px 4px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "6px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#f8fafc]',
  '[--epr-text-color:#475569]',
  '[--epr-highlight-color:#0f172a]',
  '[--epr-hover-bg-color:#e2e8f0]',
  '[--epr-focus-bg-color:#cbd5e1]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#cbd5e1]',
  '[--epr-search-border-color-active:#0f172a]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:#0f172a]',
  '[--epr-search-input-placeholder-color:#64748b]',
  '[--epr-category-label-bg-color:#f8fafcf2]',
  '[--epr-category-label-text-color:#475569]',
  '[--epr-category-label-height:28px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:10px]',
  '[height:250px]',
  '[margin-top:12px]',
  '[border:1px_solid_#e2e8f0]',
  '[border-radius:10px]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#f8fafc",
  "--muted-foreground": "#475569",
  "--primary": "#0f172a",
  "--accent": "#e2e8f0",
  "--input": "#cbd5e1",
  "--ring": "#0f172a",
  "--popover-foreground": "#0f172a"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#cbd5e1]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#64748b]',
  '[--epr-category-label-bg-color:#f8fafcf2]',
  '[--epr-category-label-text-color:#475569]',
  '[--epr-category-label-height:28px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:10px]',
  '[height:250px]',
  '[margin-top:12px]',
  '[border:1px_solid_#e2e8f0]',
  '[border-radius:10px]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
