// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Rebrand · Aurora glass',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="aurora-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: transparent;
  --epr-text-color: #f4f6ff;
  --epr-highlight-color: #8ef6e4;
  --epr-hover-bg-color: rgb(255 255 255 / 16%);
  --epr-focus-bg-color: rgb(142 246 228 / 26%);
  --epr-search-input-bg-color: rgb(255 255 255 / 12%);
  --epr-search-input-bg-color-active: rgb(255 255 255 / 18%);
  --epr-search-border-color: rgb(255 255 255 / 22%);
  --epr-search-border-color-active: #8ef6e4;
  --epr-search-input-text-color: #ffffff;
  --epr-search-input-placeholder-color: #d9defc;
  --epr-search-input-height: 44px;
  --epr-search-input-border-radius: 22px;
  --epr-search-input-padding: 0 18px 0 42px;
  --epr-category-label-bg-color: transparent;
  --epr-category-label-text-color: #ffffff;
  --epr-category-label-height: 34px;
  --epr-category-icon-active-color: #8ef6e4;
  --epr-category-icon-inactive-color: #dfe4ff;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-variation-picker-bg-color: #1a1f45;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  position: relative;
  width: 380px;
  height: 470px;
  border: 1px solid rgb(255 255 255 / 24%);
  border-radius: 28px;
  background: linear-gradient(160deg, rgb(255 255 255 / 16%), rgb(255 255 255 / 6%));
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 30%), 0 30px 60px rgb(3 6 25 / 55%);
  backdrop-filter: blur(28px) saturate(140%);
  font-family: 'Avenir Next', 'Segoe UI', 'Helvetica Neue', sans-serif;

  & [data-epr-part='search'] > * {
    padding: 18px 18px 6px;
  }

  & [data-epr-part='viewport'] {
    padding-bottom: 64px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    text-shadow: 0 1px 8px rgb(7 11 31 / 90%);
  }

  & [data-epr-part='emoji'] {
    border-radius: 14px;
  }

  & [data-epr-part='emoji']:focus-visible {
    box-shadow: 0 0 0 2px #8ef6e4, 0 0 18px rgb(142 246 228 / 60%);
  }

  & [data-epr-part='category-nav'] > * {
    gap: 4px;
    padding: 6px 10px;
  }

  & [data-epr-part='category-tab'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    background-color: rgb(142 246 228 / 18%);
    box-shadow: 0 0 14px rgb(142 246 228 / 55%);
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: transparent;
  --epr-text-color: #f4f6ff;
  --epr-highlight-color: #8ef6e4;
  --epr-hover-bg-color: rgb(255 255 255 / 16%);
  --epr-focus-bg-color: rgb(142 246 228 / 26%);
  --epr-search-input-bg-color: rgb(255 255 255 / 12%);
  --epr-search-input-bg-color-active: rgb(255 255 255 / 18%);
  --epr-search-border-color: rgb(255 255 255 / 22%);
  --epr-search-border-color-active: #8ef6e4;
  --epr-search-input-text-color: #ffffff;
  --epr-search-input-placeholder-color: #d9defc;
  --epr-search-input-height: 44px;
  --epr-search-input-border-radius: 22px;
  --epr-search-input-padding: 0 18px 0 42px;
  --epr-category-label-bg-color: transparent;
  --epr-category-label-text-color: #ffffff;
  --epr-category-label-height: 34px;
  --epr-category-icon-active-color: #8ef6e4;
  --epr-category-icon-inactive-color: #dfe4ff;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-variation-picker-bg-color: #1a1f45;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  position: relative;
  width: 380px;
  height: 470px;
  border: 1px solid rgb(255 255 255 / 24%);
  border-radius: 28px;
  background: linear-gradient(160deg, rgb(255 255 255 / 16%), rgb(255 255 255 / 6%));
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 30%), 0 30px 60px rgb(3 6 25 / 55%);
  backdrop-filter: blur(28px) saturate(140%);
  font-family: 'Avenir Next', 'Segoe UI', 'Helvetica Neue', sans-serif;

  & [data-epr-part='search'] > * {
    padding: 18px 18px 6px;
  }

  & [data-epr-part='viewport'] {
    padding-bottom: 64px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    text-shadow: 0 1px 8px rgb(7 11 31 / 90%);
  }

  & [data-epr-part='emoji'] {
    border-radius: 14px;
  }

  & [data-epr-part='emoji']:focus-visible {
    box-shadow: 0 0 0 2px #8ef6e4, 0 0 18px rgb(142 246 228 / 60%);
  }

  & [data-epr-part='category-nav'] > * {
    gap: 4px;
    padding: 6px 10px;
  }

  & [data-epr-part='category-tab'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    background-color: rgb(142 246 228 / 18%);
    box-shadow: 0 0 14px rgb(142 246 228 / 55%);
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "transparent",
  "--epr-text-color": "#f4f6ff",
  "--epr-highlight-color": "#8ef6e4",
  "--epr-hover-bg-color": "rgb(255 255 255 / 16%)",
  "--epr-focus-bg-color": "rgb(142 246 228 / 26%)",
  "--epr-search-input-bg-color": "rgb(255 255 255 / 12%)",
  "--epr-search-input-bg-color-active": "rgb(255 255 255 / 18%)",
  "--epr-search-border-color": "rgb(255 255 255 / 22%)",
  "--epr-search-border-color-active": "#8ef6e4",
  "--epr-search-input-text-color": "#ffffff",
  "--epr-search-input-placeholder-color": "#d9defc",
  "--epr-search-input-height": "44px",
  "--epr-search-input-border-radius": "22px",
  "--epr-search-input-padding": "0 18px 0 42px",
  "--epr-category-label-bg-color": "transparent",
  "--epr-category-label-text-color": "#ffffff",
  "--epr-category-label-height": "34px",
  "--epr-category-icon-active-color": "#8ef6e4",
  "--epr-category-icon-inactive-color": "#dfe4ff",
  "--epr-category-navigation-button-size": "22px",
  "--epr-emoji-variation-picker-bg-color": "#1a1f45",
  "--epr-emoji-size": "30px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "16px",
  position: "relative",
  width: "380px",
  height: "470px",
  border: "1px solid rgb(255 255 255 / 24%)",
  borderRadius: "28px",
  background: "linear-gradient(160deg, rgb(255 255 255 / 16%), rgb(255 255 255 / 6%))",
  boxShadow: "inset 0 1px 0 rgb(255 255 255 / 30%), 0 30px 60px rgb(3 6 25 / 55%)",
  backdropFilter: "blur(28px) saturate(140%)",
  fontFamily: "'Avenir Next', 'Segoe UI', 'Helvetica Neue', sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "18px 18px 6px",
  },
  "& [data-epr-part='viewport']": {
    paddingBottom: "64px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "13px",
    fontWeight: "600",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    textShadow: "0 1px 8px rgb(7 11 31 / 90%)",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "14px",
  },
  "& [data-epr-part='emoji']:focus-visible": {
    boxShadow: "0 0 0 2px #8ef6e4, 0 0 18px rgb(142 246 228 / 60%)",
  },
  "& [data-epr-part='category-nav'] > *": {
    gap: "4px",
    padding: "6px 10px",
  },
  "& [data-epr-part='category-tab']": {
    borderRadius: "50%",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    backgroundColor: "rgb(142 246 228 / 18%)",
    boxShadow: "0 0 14px rgb(142 246 228 / 55%)",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:transparent]',
  '[--epr-text-color:#f4f6ff]',
  '[--epr-highlight-color:#8ef6e4]',
  '[--epr-hover-bg-color:rgb(255_255_255_/_16%)]',
  '[--epr-focus-bg-color:rgb(142_246_228_/_26%)]',
  '[--epr-search-input-bg-color:rgb(255_255_255_/_12%)]',
  '[--epr-search-input-bg-color-active:rgb(255_255_255_/_18%)]',
  '[--epr-search-border-color:rgb(255_255_255_/_22%)]',
  '[--epr-search-border-color-active:#8ef6e4]',
  '[--epr-search-input-text-color:#ffffff]',
  '[--epr-search-input-placeholder-color:#d9defc]',
  '[--epr-search-input-height:44px]',
  '[--epr-search-input-border-radius:22px]',
  '[--epr-search-input-padding:0_18px_0_42px]',
  '[--epr-category-label-bg-color:transparent]',
  '[--epr-category-label-text-color:#ffffff]',
  '[--epr-category-label-height:34px]',
  '[--epr-category-icon-active-color:#8ef6e4]',
  '[--epr-category-icon-inactive-color:#dfe4ff]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-variation-picker-bg-color:#1a1f45]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[position:relative]',
  '[width:380px]',
  '[height:470px]',
  '[border:1px_solid_rgb(255_255_255_/_24%)]',
  '[border-radius:28px]',
  '[background:linear-gradient(160deg,_rgb(255_255_255_/_16%),_rgb(255_255_255_/_6%))]',
  '[box-shadow:inset_0_1px_0_rgb(255_255_255_/_30%),_0_30px_60px_rgb(3_6_25_/_55%)]',
  '[backdrop-filter:blur(28px)_saturate(140%)]',
  "[font-family:'Avenir_Next',_'Segoe_UI',_'Helvetica_Neue',_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:18px_18px_6px]',
  '[&_[data-epr-part=viewport]]:[padding-bottom:64px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.12em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=category-label]]:[text-shadow:0_1px_8px_rgb(7_11_31_/_90%)]',
  '[&_[data-epr-part=emoji]]:[border-radius:14px]',
  '[&_[data-epr-part=emoji]:focus-visible]:[box-shadow:0_0_0_2px_#8ef6e4,_0_0_18px_rgb(142_246_228_/_60%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:50%]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:rgb(142_246_228_/_18%)]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_0_14px_rgb(142_246_228_/_55%)]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "transparent",
  "--muted-foreground": "#f4f6ff",
  "--primary": "#8ef6e4",
  "--accent": "rgb(255 255 255 / 16%)",
  "--input": "rgb(255 255 255 / 22%)",
  "--ring": "#8ef6e4",
  "--popover-foreground": "#ffffff"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:rgb(142_246_228_/_26%)]',
  '[--epr-search-input-bg-color:rgb(255_255_255_/_12%)]',
  '[--epr-search-input-bg-color-active:rgb(255_255_255_/_18%)]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#d9defc]',
  '[--epr-search-input-height:44px]',
  '[--epr-search-input-border-radius:22px]',
  '[--epr-search-input-padding:0_18px_0_42px]',
  '[--epr-category-label-bg-color:transparent]',
  '[--epr-category-label-text-color:#ffffff]',
  '[--epr-category-label-height:34px]',
  '[--epr-category-icon-active-color:#8ef6e4]',
  '[--epr-category-icon-inactive-color:#dfe4ff]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-variation-picker-bg-color:#1a1f45]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[position:relative]',
  '[width:380px]',
  '[height:470px]',
  '[border:1px_solid_rgb(255_255_255_/_24%)]',
  '[border-radius:28px]',
  '[background:linear-gradient(160deg,_rgb(255_255_255_/_16%),_rgb(255_255_255_/_6%))]',
  '[box-shadow:inset_0_1px_0_rgb(255_255_255_/_30%),_0_30px_60px_rgb(3_6_25_/_55%)]',
  '[backdrop-filter:blur(28px)_saturate(140%)]',
  "[font-family:'Avenir_Next',_'Segoe_UI',_'Helvetica_Neue',_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:18px_18px_6px]',
  '[&_[data-epr-part=viewport]]:[padding-bottom:64px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.12em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=category-label]]:[text-shadow:0_1px_8px_rgb(7_11_31_/_90%)]',
  '[&_[data-epr-part=emoji]]:[border-radius:14px]',
  '[&_[data-epr-part=emoji]:focus-visible]:[box-shadow:0_0_0_2px_#8ef6e4,_0_0_18px_rgb(142_246_228_/_60%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:50%]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:rgb(142_246_228_/_18%)]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_0_14px_rgb(142_246_228_/_55%)]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
