// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/iOS bottom sheet',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="ios-sheet" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #f2f2f7;
  --epr-text-color: #3c3c43;
  --epr-highlight-color: #007aff;
  --epr-hover-bg-color: rgb(120 120 128 / 16%);
  --epr-focus-bg-color: rgb(120 120 128 / 20%);
  --epr-category-label-height: 0px;
  --epr-category-icon-active-color: #007aff;
  --epr-category-icon-inactive-color: #8e8e93;
  --epr-category-navigation-button-size: 26px;
  --epr-emoji-size: 34px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  height: 100%;
  border-radius: 16px 16px 0 0;
  background: var(--epr-bg-color);
  box-shadow: 0 -4px 24px rgb(0 0 0 / 18%);

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 10px;
  }

  & [data-epr-part='category-nav'] {
    border-top: 0.5px solid rgb(60 60 67 / 29%);
    background: rgb(249 249 249 / 94%);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 10px 22px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #f2f2f7;
  --epr-text-color: #3c3c43;
  --epr-highlight-color: #007aff;
  --epr-hover-bg-color: rgb(120 120 128 / 16%);
  --epr-focus-bg-color: rgb(120 120 128 / 20%);
  --epr-category-label-height: 0px;
  --epr-category-icon-active-color: #007aff;
  --epr-category-icon-inactive-color: #8e8e93;
  --epr-category-navigation-button-size: 26px;
  --epr-emoji-size: 34px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  height: 100%;
  border-radius: 16px 16px 0 0;
  background: var(--epr-bg-color);
  box-shadow: 0 -4px 24px rgb(0 0 0 / 18%);

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 10px;
  }

  & [data-epr-part='category-nav'] {
    border-top: 0.5px solid rgb(60 60 67 / 29%);
    background: rgb(249 249 249 / 94%);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 10px 22px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#f2f2f7",
  "--epr-text-color": "#3c3c43",
  "--epr-highlight-color": "#007aff",
  "--epr-hover-bg-color": "rgb(120 120 128 / 16%)",
  "--epr-focus-bg-color": "rgb(120 120 128 / 20%)",
  "--epr-category-label-height": "0px",
  "--epr-category-icon-active-color": "#007aff",
  "--epr-category-icon-inactive-color": "#8e8e93",
  "--epr-category-navigation-button-size": "26px",
  "--epr-emoji-size": "34px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "12px",
  height: "100%",
  borderRadius: "16px 16px 0 0",
  background: "var(--epr-bg-color)",
  boxShadow: "0 -4px 24px rgb(0 0 0 / 18%)",
  "& [data-epr-part='category-label']": {
    display: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "10px",
  },
  "& [data-epr-part='category-nav']": {
    borderTop: "0.5px solid rgb(60 60 67 / 29%)",
    background: "rgb(249 249 249 / 94%)",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "8px 10px 22px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#f2f2f7]',
  '[--epr-text-color:#3c3c43]',
  '[--epr-highlight-color:#007aff]',
  '[--epr-hover-bg-color:rgb(120_120_128_/_16%)]',
  '[--epr-focus-bg-color:rgb(120_120_128_/_20%)]',
  '[--epr-category-label-height:0px]',
  '[--epr-category-icon-active-color:#007aff]',
  '[--epr-category-icon-inactive-color:#8e8e93]',
  '[--epr-category-navigation-button-size:26px]',
  '[--epr-emoji-size:34px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[height:100%]',
  '[border-radius:16px_16px_0_0]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_-4px_24px_rgb(0_0_0_/_18%)]',
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:10px]',
  '[&_[data-epr-part=category-nav]]:[border-top:0.5px_solid_rgb(60_60_67_/_29%)]',
  '[&_[data-epr-part=category-nav]]:[background:rgb(249_249_249_/_94%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_10px_22px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#f2f2f7",
  "--muted-foreground": "#3c3c43",
  "--primary": "#007aff",
  "--accent": "rgb(120 120 128 / 16%)"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:rgb(120_120_128_/_20%)]',
  '[--epr-category-label-height:0px]',
  '[--epr-category-icon-active-color:#007aff]',
  '[--epr-category-icon-inactive-color:#8e8e93]',
  '[--epr-category-navigation-button-size:26px]',
  '[--epr-emoji-size:34px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[height:100%]',
  '[border-radius:16px_16px_0_0]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_-4px_24px_rgb(0_0_0_/_18%)]',
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:10px]',
  '[&_[data-epr-part=category-nav]]:[border-top:0.5px_solid_rgb(60_60_67_/_29%)]',
  '[&_[data-epr-part=category-nav]]:[background:rgb(249_249_249_/_94%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_10px_22px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
