// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Rebrand · Neo-brutal zine',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="zine-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #fff7e8;
  --epr-text-color: #111111;
  --epr-highlight-color: #111111;
  --epr-hover-bg-color: #ffd23f;
  --epr-focus-bg-color: #7cf0c5;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #111111;
  --epr-search-border-color-active: #111111;
  --epr-search-input-text-color: #111111;
  --epr-search-input-placeholder-color: #4a4a4a;
  --epr-search-input-height: 44px;
  --epr-search-input-border-radius: 0;
  --epr-category-label-bg-color: transparent;
  --epr-category-label-height: 44px;
  --epr-category-icon-active-color: #111111;
  --epr-category-icon-inactive-color: #4a4a4a;
  --epr-category-navigation-button-size: 26px;
  --epr-emoji-variation-picker-bg-color: #ffffff;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 14px;
  width: 380px;
  height: 480px;
  border: 3px solid #111111;
  background: var(--epr-bg-color);
  box-shadow: 10px 10px 0 #111111;
  font-family: 'Arial Black', 'Helvetica Neue', Impact, sans-serif;

  & [data-epr-part='search'] input {
    border-width: 3px;
    font-family: 'Courier New', monospace;
    font-weight: 700;
    letter-spacing: 0.06em;
  }

  & [data-epr-part='category-nav'] {
    border-top: 3px solid #111111;
    border-bottom: 3px solid #111111;
    background: #7cf0c5;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    outline: 3px solid #111111;
    outline-offset: 2px;
    background-color: #ffffff;
  }

  & .zine-sticker {
    margin: 0;
    padding: 0 14px;
    background: transparent;
    backdrop-filter: none;
  }

  & .zine-sticker span {
    padding: 4px 10px;
    border: 3px solid #111111;
    background: #ff5ca8;
    box-shadow: 4px 4px 0 #111111;
    color: #111111;
    font-size: 13px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    transform: rotate(-2deg);
  }

  & .zine-tile {
    border: 2px solid #111111;
    border-radius: 0;
    background: #ffffff;
  }

  & .zine-tile:hover,
  & .zine-tile:focus {
    box-shadow: 3px 3px 0 #111111;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #fff7e8;
  --epr-text-color: #111111;
  --epr-highlight-color: #111111;
  --epr-hover-bg-color: #ffd23f;
  --epr-focus-bg-color: #7cf0c5;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #111111;
  --epr-search-border-color-active: #111111;
  --epr-search-input-text-color: #111111;
  --epr-search-input-placeholder-color: #4a4a4a;
  --epr-search-input-height: 44px;
  --epr-search-input-border-radius: 0;
  --epr-category-label-bg-color: transparent;
  --epr-category-label-height: 44px;
  --epr-category-icon-active-color: #111111;
  --epr-category-icon-inactive-color: #4a4a4a;
  --epr-category-navigation-button-size: 26px;
  --epr-emoji-variation-picker-bg-color: #ffffff;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 14px;
  width: 380px;
  height: 480px;
  border: 3px solid #111111;
  background: var(--epr-bg-color);
  box-shadow: 10px 10px 0 #111111;
  font-family: 'Arial Black', 'Helvetica Neue', Impact, sans-serif;

  & [data-epr-part='search'] input {
    border-width: 3px;
    font-family: 'Courier New', monospace;
    font-weight: 700;
    letter-spacing: 0.06em;
  }

  & [data-epr-part='category-nav'] {
    border-top: 3px solid #111111;
    border-bottom: 3px solid #111111;
    background: #7cf0c5;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    outline: 3px solid #111111;
    outline-offset: 2px;
    background-color: #ffffff;
  }

  & .zine-sticker {
    margin: 0;
    padding: 0 14px;
    background: transparent;
    backdrop-filter: none;
  }

  & .zine-sticker span {
    padding: 4px 10px;
    border: 3px solid #111111;
    background: #ff5ca8;
    box-shadow: 4px 4px 0 #111111;
    color: #111111;
    font-size: 13px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    transform: rotate(-2deg);
  }

  & .zine-tile {
    border: 2px solid #111111;
    border-radius: 0;
    background: #ffffff;
  }

  & .zine-tile:hover,
  & .zine-tile:focus {
    box-shadow: 3px 3px 0 #111111;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#fff7e8",
  "--epr-text-color": "#111111",
  "--epr-highlight-color": "#111111",
  "--epr-hover-bg-color": "#ffd23f",
  "--epr-focus-bg-color": "#7cf0c5",
  "--epr-search-input-bg-color": "#ffffff",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#111111",
  "--epr-search-border-color-active": "#111111",
  "--epr-search-input-text-color": "#111111",
  "--epr-search-input-placeholder-color": "#4a4a4a",
  "--epr-search-input-height": "44px",
  "--epr-search-input-border-radius": "0",
  "--epr-category-label-bg-color": "transparent",
  "--epr-category-label-height": "44px",
  "--epr-category-icon-active-color": "#111111",
  "--epr-category-icon-inactive-color": "#4a4a4a",
  "--epr-category-navigation-button-size": "26px",
  "--epr-emoji-variation-picker-bg-color": "#ffffff",
  "--epr-emoji-size": "28px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "14px",
  width: "380px",
  height: "480px",
  border: "3px solid #111111",
  background: "var(--epr-bg-color)",
  boxShadow: "10px 10px 0 #111111",
  fontFamily: "'Arial Black', 'Helvetica Neue', Impact, sans-serif",
  "& [data-epr-part='search'] input": {
    borderWidth: "3px",
    fontFamily: "'Courier New', monospace",
    fontWeight: "700",
    letterSpacing: "0.06em",
  },
  "& [data-epr-part='category-nav']": {
    borderTop: "3px solid #111111",
    borderBottom: "3px solid #111111",
    background: "#7cf0c5",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    outline: "3px solid #111111",
    outlineOffset: "2px",
    backgroundColor: "#ffffff",
  },
  "& .zine-sticker": {
    margin: "0",
    padding: "0 14px",
    background: "transparent",
    backdropFilter: "none",
  },
  "& .zine-sticker span": {
    padding: "4px 10px",
    border: "3px solid #111111",
    background: "#ff5ca8",
    boxShadow: "4px 4px 0 #111111",
    color: "#111111",
    fontSize: "13px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    transform: "rotate(-2deg)",
  },
  "& .zine-tile": {
    border: "2px solid #111111",
    borderRadius: "0",
    background: "#ffffff",
  },
  "& .zine-tile:hover, & .zine-tile:focus": {
    boxShadow: "3px 3px 0 #111111",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#fff7e8]',
  '[--epr-text-color:#111111]',
  '[--epr-highlight-color:#111111]',
  '[--epr-hover-bg-color:#ffd23f]',
  '[--epr-focus-bg-color:#7cf0c5]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#111111]',
  '[--epr-search-border-color-active:#111111]',
  '[--epr-search-input-text-color:#111111]',
  '[--epr-search-input-placeholder-color:#4a4a4a]',
  '[--epr-search-input-height:44px]',
  '[--epr-search-input-border-radius:0]',
  '[--epr-category-label-bg-color:transparent]',
  '[--epr-category-label-height:44px]',
  '[--epr-category-icon-active-color:#111111]',
  '[--epr-category-icon-inactive-color:#4a4a4a]',
  '[--epr-category-navigation-button-size:26px]',
  '[--epr-emoji-variation-picker-bg-color:#ffffff]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:14px]',
  '[width:380px]',
  '[height:480px]',
  '[border:3px_solid_#111111]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:10px_10px_0_#111111]',
  "[font-family:'Arial_Black',_'Helvetica_Neue',_Impact,_sans-serif]",
  '[&_[data-epr-part=search]_input]:[border-width:3px]',
  "[&_[data-epr-part=search]_input]:[font-family:'Courier_New',_monospace]",
  '[&_[data-epr-part=search]_input]:[font-weight:700]',
  '[&_[data-epr-part=search]_input]:[letter-spacing:0.06em]',
  '[&_[data-epr-part=category-nav]]:[border-top:3px_solid_#111111]',
  '[&_[data-epr-part=category-nav]]:[border-bottom:3px_solid_#111111]',
  '[&_[data-epr-part=category-nav]]:[background:#7cf0c5]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline:3px_solid_#111111]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline-offset:2px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#ffffff]',
  '[&_.zine-sticker]:[margin:0]',
  '[&_.zine-sticker]:[padding:0_14px]',
  '[&_.zine-sticker]:[background:transparent]',
  '[&_.zine-sticker]:[backdrop-filter:none]',
  '[&_.zine-sticker_span]:[padding:4px_10px]',
  '[&_.zine-sticker_span]:[border:3px_solid_#111111]',
  '[&_.zine-sticker_span]:[background:#ff5ca8]',
  '[&_.zine-sticker_span]:[box-shadow:4px_4px_0_#111111]',
  '[&_.zine-sticker_span]:[color:#111111]',
  '[&_.zine-sticker_span]:[font-size:13px]',
  '[&_.zine-sticker_span]:[letter-spacing:0.06em]',
  '[&_.zine-sticker_span]:[text-transform:uppercase]',
  '[&_.zine-sticker_span]:[transform:rotate(-2deg)]',
  '[&_.zine-tile]:[border:2px_solid_#111111]',
  '[&_.zine-tile]:[border-radius:0]',
  '[&_.zine-tile]:[background:#ffffff]',
  '[&_.zine-tile:hover]:[box-shadow:3px_3px_0_#111111]',
  '[&_.zine-tile:focus]:[box-shadow:3px_3px_0_#111111]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#fff7e8",
  "--muted-foreground": "#111111",
  "--primary": "#111111",
  "--accent": "#ffd23f",
  "--input": "#111111",
  "--ring": "#111111",
  "--popover-foreground": "#111111"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#7cf0c5]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#4a4a4a]',
  '[--epr-search-input-height:44px]',
  '[--epr-search-input-border-radius:0]',
  '[--epr-category-label-bg-color:transparent]',
  '[--epr-category-label-height:44px]',
  '[--epr-category-icon-active-color:#111111]',
  '[--epr-category-icon-inactive-color:#4a4a4a]',
  '[--epr-category-navigation-button-size:26px]',
  '[--epr-emoji-variation-picker-bg-color:#ffffff]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:14px]',
  '[width:380px]',
  '[height:480px]',
  '[border:3px_solid_#111111]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:10px_10px_0_#111111]',
  "[font-family:'Arial_Black',_'Helvetica_Neue',_Impact,_sans-serif]",
  '[&_[data-epr-part=search]_input]:[border-width:3px]',
  "[&_[data-epr-part=search]_input]:[font-family:'Courier_New',_monospace]",
  '[&_[data-epr-part=search]_input]:[font-weight:700]',
  '[&_[data-epr-part=search]_input]:[letter-spacing:0.06em]',
  '[&_[data-epr-part=category-nav]]:[border-top:3px_solid_#111111]',
  '[&_[data-epr-part=category-nav]]:[border-bottom:3px_solid_#111111]',
  '[&_[data-epr-part=category-nav]]:[background:#7cf0c5]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline:3px_solid_#111111]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[outline-offset:2px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#ffffff]',
  '[&_.zine-sticker]:[margin:0]',
  '[&_.zine-sticker]:[padding:0_14px]',
  '[&_.zine-sticker]:[background:transparent]',
  '[&_.zine-sticker]:[backdrop-filter:none]',
  '[&_.zine-sticker_span]:[padding:4px_10px]',
  '[&_.zine-sticker_span]:[border:3px_solid_#111111]',
  '[&_.zine-sticker_span]:[background:#ff5ca8]',
  '[&_.zine-sticker_span]:[box-shadow:4px_4px_0_#111111]',
  '[&_.zine-sticker_span]:[color:#111111]',
  '[&_.zine-sticker_span]:[font-size:13px]',
  '[&_.zine-sticker_span]:[letter-spacing:0.06em]',
  '[&_.zine-sticker_span]:[text-transform:uppercase]',
  '[&_.zine-sticker_span]:[transform:rotate(-2deg)]',
  '[&_.zine-tile]:[border:2px_solid_#111111]',
  '[&_.zine-tile]:[border-radius:0]',
  '[&_.zine-tile]:[background:#ffffff]',
  '[&_.zine-tile:hover]:[box-shadow:3px_3px_0_#111111]',
  '[&_.zine-tile:focus]:[box-shadow:3px_3px_0_#111111]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
