// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Livestream chat',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="stream-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #1f1f23;
  --epr-text-color: #c8c8d0;
  --epr-highlight-color: #bf94ff;
  --epr-hover-bg-color: #2f2f35;
  --epr-focus-bg-color: #3d3d44;
  --epr-search-input-bg-color: #0e0e10;
  --epr-search-input-bg-color-active: #0e0e10;
  --epr-search-border-color: #3d3d44;
  --epr-search-border-color-active: #bf94ff;
  --epr-search-input-height: 30px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-text-color: #efeff1;
  --epr-search-input-placeholder-color: #a8a8b3;
  --epr-category-label-bg-color: #1f1f23f2;
  --epr-category-label-text-color: #c8c8d0;
  --epr-category-label-height: 26px;
  --epr-category-icon-active-color: #bf94ff;
  --epr-category-icon-inactive-color: #a8a8b3;
  --epr-category-navigation-button-size: 18px;
  --epr-emoji-variation-picker-bg-color: #2f2f35;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 4px;
  --epr-horizontal-padding: 10px;
  height: 230px;
  border-top: 1px solid #2f2f35;
  background: var(--epr-bg-color);

  & [data-epr-part='category-nav'] > * {
    padding: 8px 10px 4px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 9px 0 -7px #bf94ff;
  }

  & [data-epr-part='search'] > * {
    padding: 4px 10px;
  }

  & [data-epr-part='category-label'] {
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #1f1f23;
  --epr-text-color: #c8c8d0;
  --epr-highlight-color: #bf94ff;
  --epr-hover-bg-color: #2f2f35;
  --epr-focus-bg-color: #3d3d44;
  --epr-search-input-bg-color: #0e0e10;
  --epr-search-input-bg-color-active: #0e0e10;
  --epr-search-border-color: #3d3d44;
  --epr-search-border-color-active: #bf94ff;
  --epr-search-input-height: 30px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-text-color: #efeff1;
  --epr-search-input-placeholder-color: #a8a8b3;
  --epr-category-label-bg-color: #1f1f23f2;
  --epr-category-label-text-color: #c8c8d0;
  --epr-category-label-height: 26px;
  --epr-category-icon-active-color: #bf94ff;
  --epr-category-icon-inactive-color: #a8a8b3;
  --epr-category-navigation-button-size: 18px;
  --epr-emoji-variation-picker-bg-color: #2f2f35;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 4px;
  --epr-horizontal-padding: 10px;
  height: 230px;
  border-top: 1px solid #2f2f35;
  background: var(--epr-bg-color);

  & [data-epr-part='category-nav'] > * {
    padding: 8px 10px 4px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 9px 0 -7px #bf94ff;
  }

  & [data-epr-part='search'] > * {
    padding: 4px 10px;
  }

  & [data-epr-part='category-label'] {
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#1f1f23",
  "--epr-text-color": "#c8c8d0",
  "--epr-highlight-color": "#bf94ff",
  "--epr-hover-bg-color": "#2f2f35",
  "--epr-focus-bg-color": "#3d3d44",
  "--epr-search-input-bg-color": "#0e0e10",
  "--epr-search-input-bg-color-active": "#0e0e10",
  "--epr-search-border-color": "#3d3d44",
  "--epr-search-border-color-active": "#bf94ff",
  "--epr-search-input-height": "30px",
  "--epr-search-input-border-radius": "6px",
  "--epr-search-input-text-color": "#efeff1",
  "--epr-search-input-placeholder-color": "#a8a8b3",
  "--epr-category-label-bg-color": "#1f1f23f2",
  "--epr-category-label-text-color": "#c8c8d0",
  "--epr-category-label-height": "26px",
  "--epr-category-icon-active-color": "#bf94ff",
  "--epr-category-icon-inactive-color": "#a8a8b3",
  "--epr-category-navigation-button-size": "18px",
  "--epr-emoji-variation-picker-bg-color": "#2f2f35",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "4px",
  "--epr-horizontal-padding": "10px",
  height: "230px",
  borderTop: "1px solid #2f2f35",
  background: "var(--epr-bg-color)",
  "& [data-epr-part='category-nav'] > *": {
    padding: "8px 10px 4px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    boxShadow: "0 9px 0 -7px #bf94ff",
  },
  "& [data-epr-part='search'] > *": {
    padding: "4px 10px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "4px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#1f1f23]',
  '[--epr-text-color:#c8c8d0]',
  '[--epr-highlight-color:#bf94ff]',
  '[--epr-hover-bg-color:#2f2f35]',
  '[--epr-focus-bg-color:#3d3d44]',
  '[--epr-search-input-bg-color:#0e0e10]',
  '[--epr-search-input-bg-color-active:#0e0e10]',
  '[--epr-search-border-color:#3d3d44]',
  '[--epr-search-border-color-active:#bf94ff]',
  '[--epr-search-input-height:30px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-text-color:#efeff1]',
  '[--epr-search-input-placeholder-color:#a8a8b3]',
  '[--epr-category-label-bg-color:#1f1f23f2]',
  '[--epr-category-label-text-color:#c8c8d0]',
  '[--epr-category-label-height:26px]',
  '[--epr-category-icon-active-color:#bf94ff]',
  '[--epr-category-icon-inactive-color:#a8a8b3]',
  '[--epr-category-navigation-button-size:18px]',
  '[--epr-emoji-variation-picker-bg-color:#2f2f35]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:4px]',
  '[--epr-horizontal-padding:10px]',
  '[height:230px]',
  '[border-top:1px_solid_#2f2f35]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_10px_4px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_9px_0_-7px_#bf94ff]',
  '[&_[data-epr-part=search]_>_*]:[padding:4px_10px]',
  '[&_[data-epr-part=category-label]]:[font-size:11px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.05em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#1f1f23",
  "--muted-foreground": "#c8c8d0",
  "--primary": "#bf94ff",
  "--accent": "#2f2f35",
  "--input": "#3d3d44",
  "--ring": "#bf94ff",
  "--popover-foreground": "#efeff1"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#3d3d44]',
  '[--epr-search-input-bg-color:#0e0e10]',
  '[--epr-search-input-bg-color-active:#0e0e10]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:30px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#a8a8b3]',
  '[--epr-category-label-bg-color:#1f1f23f2]',
  '[--epr-category-label-text-color:#c8c8d0]',
  '[--epr-category-label-height:26px]',
  '[--epr-category-icon-active-color:#bf94ff]',
  '[--epr-category-icon-inactive-color:#a8a8b3]',
  '[--epr-category-navigation-button-size:18px]',
  '[--epr-emoji-variation-picker-bg-color:#2f2f35]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:4px]',
  '[--epr-horizontal-padding:10px]',
  '[height:230px]',
  '[border-top:1px_solid_#2f2f35]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_10px_4px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_9px_0_-7px_#bf94ff]',
  '[&_[data-epr-part=search]_>_*]:[padding:4px_10px]',
  '[&_[data-epr-part=category-label]]:[font-size:11px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.05em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
