// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Geist minimal',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="geist-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-highlight-color: #000000;
  --epr-text-color: #666666;
  --epr-hover-bg-color: #f2f2f2;
  --epr-focus-bg-color: #ebebeb;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #eaeaea;
  --epr-search-border-color-active: #000000;
  --epr-search-input-height: 36px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-padding: 0 12px 0 34px;
  --epr-category-icon-active-color: #000000;
  --epr-category-icon-inactive-color: #a1a1a1;
  --epr-category-navigation-button-size: 20px;
  --epr-category-label-height: 32px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 12px;
  width: 336px;
  height: 400px;
  border: 1px solid #eaeaea;
  border-radius: 12px;
  background: #fff;
  box-shadow: 0 4px 12px rgb(0 0 0 / 8%);
  font-family: Geist, Inter, -apple-system, 'Segoe UI', sans-serif;

  & [data-epr-part='search'] > * {
    padding: 12px 12px 8px;
  }

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #eaeaea;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 4px 12px 10px;
  }

  & .geist-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0;
    color: #6b6b6b;
    font-family: 'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 11px;
    font-weight: 500;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }

  & .geist-header::after {
    content: '';
    flex: 1;
    border-top: 1px solid #eaeaea;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & [data-epr-part='emoji']:focus-visible {
    outline: 2px solid #000;
    outline-offset: -2px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-highlight-color: #000000;
  --epr-text-color: #666666;
  --epr-hover-bg-color: #f2f2f2;
  --epr-focus-bg-color: #ebebeb;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #eaeaea;
  --epr-search-border-color-active: #000000;
  --epr-search-input-height: 36px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-padding: 0 12px 0 34px;
  --epr-category-icon-active-color: #000000;
  --epr-category-icon-inactive-color: #a1a1a1;
  --epr-category-navigation-button-size: 20px;
  --epr-category-label-height: 32px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 12px;
  width: 336px;
  height: 400px;
  border: 1px solid #eaeaea;
  border-radius: 12px;
  background: #fff;
  box-shadow: 0 4px 12px rgb(0 0 0 / 8%);
  font-family: Geist, Inter, -apple-system, 'Segoe UI', sans-serif;

  & [data-epr-part='search'] > * {
    padding: 12px 12px 8px;
  }

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #eaeaea;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 4px 12px 10px;
  }

  & .geist-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0;
    color: #6b6b6b;
    font-family: 'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 11px;
    font-weight: 500;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }

  & .geist-header::after {
    content: '';
    flex: 1;
    border-top: 1px solid #eaeaea;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & [data-epr-part='emoji']:focus-visible {
    outline: 2px solid #000;
    outline-offset: -2px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-highlight-color": "#000000",
  "--epr-text-color": "#666666",
  "--epr-hover-bg-color": "#f2f2f2",
  "--epr-focus-bg-color": "#ebebeb",
  "--epr-search-input-bg-color": "#ffffff",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#eaeaea",
  "--epr-search-border-color-active": "#000000",
  "--epr-search-input-height": "36px",
  "--epr-search-input-border-radius": "6px",
  "--epr-search-input-padding": "0 12px 0 34px",
  "--epr-category-icon-active-color": "#000000",
  "--epr-category-icon-inactive-color": "#a1a1a1",
  "--epr-category-navigation-button-size": "20px",
  "--epr-category-label-height": "32px",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "12px",
  width: "336px",
  height: "400px",
  border: "1px solid #eaeaea",
  borderRadius: "12px",
  background: "#fff",
  boxShadow: "0 4px 12px rgb(0 0 0 / 8%)",
  fontFamily: "Geist, Inter, -apple-system, 'Segoe UI', sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "12px 12px 8px",
  },
  "& [data-epr-part='category-nav']": {
    borderBottom: "1px solid #eaeaea",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "4px 12px 10px",
  },
  "& .geist-header": {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "0",
    color: "#6b6b6b",
    fontFamily: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    fontWeight: "500",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  "& .geist-header::after": {
    content: "''",
    flex: "1",
    borderTop: "1px solid #eaeaea",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "6px",
  },
  "& [data-epr-part='emoji']:focus-visible": {
    outline: "2px solid #000",
    outlineOffset: "-2px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-highlight-color:#000000]',
  '[--epr-text-color:#666666]',
  '[--epr-hover-bg-color:#f2f2f2]',
  '[--epr-focus-bg-color:#ebebeb]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#eaeaea]',
  '[--epr-search-border-color-active:#000000]',
  '[--epr-search-input-height:36px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-padding:0_12px_0_34px]',
  '[--epr-category-icon-active-color:#000000]',
  '[--epr-category-icon-inactive-color:#a1a1a1]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-category-label-height:32px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:12px]',
  '[width:336px]',
  '[height:400px]',
  '[border:1px_solid_#eaeaea]',
  '[border-radius:12px]',
  '[background:#fff]',
  '[box-shadow:0_4px_12px_rgb(0_0_0_/_8%)]',
  "[font-family:Geist,_Inter,_-apple-system,_'Segoe_UI',_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:12px_12px_8px]',
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#eaeaea]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:4px_12px_10px]',
  '[&_.geist-header]:[display:flex]',
  '[&_.geist-header]:[align-items:center]',
  '[&_.geist-header]:[gap:8px]',
  '[&_.geist-header]:[margin:0]',
  '[&_.geist-header]:[color:#6b6b6b]',
  "[&_.geist-header]:[font-family:'Geist_Mono',_ui-monospace,_SFMono-Regular,_Menlo,_monospace]",
  '[&_.geist-header]:[font-size:11px]',
  '[&_.geist-header]:[font-weight:500]',
  '[&_.geist-header]:[letter-spacing:0.06em]',
  '[&_.geist-header]:[text-transform:uppercase]',
  "[&_.geist-header::after]:[content:'']",
  '[&_.geist-header::after]:[flex:1]',
  '[&_.geist-header::after]:[border-top:1px_solid_#eaeaea]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_[data-epr-part=emoji]:focus-visible]:[outline:2px_solid_#000]',
  '[&_[data-epr-part=emoji]:focus-visible]:[outline-offset:-2px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--primary": "#000000",
  "--muted-foreground": "#666666",
  "--accent": "#f2f2f2",
  "--input": "#eaeaea",
  "--ring": "#000000"
} as React.CSSProperties;

const shadcn = [
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#ebebeb]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:36px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-padding:0_12px_0_34px]',
  '[--epr-category-icon-active-color:#000000]',
  '[--epr-category-icon-inactive-color:#a1a1a1]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-category-label-height:32px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:12px]',
  '[width:336px]',
  '[height:400px]',
  '[border:1px_solid_#eaeaea]',
  '[border-radius:12px]',
  '[background:#fff]',
  '[box-shadow:0_4px_12px_rgb(0_0_0_/_8%)]',
  "[font-family:Geist,_Inter,_-apple-system,_'Segoe_UI',_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:12px_12px_8px]',
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#eaeaea]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:4px_12px_10px]',
  '[&_.geist-header]:[display:flex]',
  '[&_.geist-header]:[align-items:center]',
  '[&_.geist-header]:[gap:8px]',
  '[&_.geist-header]:[margin:0]',
  '[&_.geist-header]:[color:#6b6b6b]',
  "[&_.geist-header]:[font-family:'Geist_Mono',_ui-monospace,_SFMono-Regular,_Menlo,_monospace]",
  '[&_.geist-header]:[font-size:11px]',
  '[&_.geist-header]:[font-weight:500]',
  '[&_.geist-header]:[letter-spacing:0.06em]',
  '[&_.geist-header]:[text-transform:uppercase]',
  "[&_.geist-header::after]:[content:'']",
  '[&_.geist-header::after]:[flex:1]',
  '[&_.geist-header::after]:[border-top:1px_solid_#eaeaea]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_[data-epr-part=emoji]:focus-visible]:[outline:2px_solid_#000]',
  '[&_[data-epr-part=emoji]:focus-visible]:[outline-offset:-2px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
