// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Shortcode typeahead',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="typeahead-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #2563eb;
  --epr-hover-bg-color: #eff6ff;
  --epr-focus-bg-color: #dbeafe;
  --epr-category-label-height: 0px;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 8px;
  width: 340px;
  height: 172px;
  margin-top: 6px;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #ffffff;
  box-shadow: 0 12px 28px rgb(17 24 39 / 14%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='list'] {
    padding-top: 6px;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }

  & .typeahead-hint {
    display: flex;
    justify-content: space-between;
    padding: 8px 12px;
    border-top: 1px solid #f3f4f6;
    color: #4b5563;
    font-size: 12px;
  }

  & .typeahead-name::first-letter {
    text-transform: uppercase;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #2563eb;
  --epr-hover-bg-color: #eff6ff;
  --epr-focus-bg-color: #dbeafe;
  --epr-category-label-height: 0px;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 8px;
  width: 340px;
  height: 172px;
  margin-top: 6px;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #ffffff;
  box-shadow: 0 12px 28px rgb(17 24 39 / 14%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='list'] {
    padding-top: 6px;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }

  & .typeahead-hint {
    display: flex;
    justify-content: space-between;
    padding: 8px 12px;
    border-top: 1px solid #f3f4f6;
    color: #4b5563;
    font-size: 12px;
  }

  & .typeahead-name::first-letter {
    text-transform: uppercase;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#4b5563",
  "--epr-highlight-color": "#2563eb",
  "--epr-hover-bg-color": "#eff6ff",
  "--epr-focus-bg-color": "#dbeafe",
  "--epr-category-label-height": "0px",
  "--epr-emoji-size": "28px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "8px",
  width: "340px",
  height: "172px",
  marginTop: "6px",
  border: "1px solid #e5e7eb",
  borderRadius: "12px",
  background: "#ffffff",
  boxShadow: "0 12px 28px rgb(17 24 39 / 14%)",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='category-label']": {
    display: "none",
  },
  "& [data-epr-part='list']": {
    paddingTop: "6px",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "8px",
  },
  "& .typeahead-hint": {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderTop: "1px solid #f3f4f6",
    color: "#4b5563",
    fontSize: "12px",
  },
  "& .typeahead-name::first-letter": {
    textTransform: "uppercase",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#4b5563]',
  '[--epr-highlight-color:#2563eb]',
  '[--epr-hover-bg-color:#eff6ff]',
  '[--epr-focus-bg-color:#dbeafe]',
  '[--epr-category-label-height:0px]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:8px]',
  '[width:340px]',
  '[height:172px]',
  '[margin-top:6px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  '[box-shadow:0_12px_28px_rgb(17_24_39_/_14%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=list]]:[padding-top:6px]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
  '[&_.typeahead-hint]:[display:flex]',
  '[&_.typeahead-hint]:[justify-content:space-between]',
  '[&_.typeahead-hint]:[padding:8px_12px]',
  '[&_.typeahead-hint]:[border-top:1px_solid_#f3f4f6]',
  '[&_.typeahead-hint]:[color:#4b5563]',
  '[&_.typeahead-hint]:[font-size:12px]',
  '[&_.typeahead-name::first-letter]:[text-transform:uppercase]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#4b5563",
  "--primary": "#2563eb",
  "--accent": "#eff6ff"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#dbeafe]',
  '[--epr-category-label-height:0px]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:8px]',
  '[width:340px]',
  '[height:172px]',
  '[margin-top:6px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  '[box-shadow:0_12px_28px_rgb(17_24_39_/_14%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=list]]:[padding-top:6px]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
  '[&_.typeahead-hint]:[display:flex]',
  '[&_.typeahead-hint]:[justify-content:space-between]',
  '[&_.typeahead-hint]:[padding:8px_12px]',
  '[&_.typeahead-hint]:[border-top:1px_solid_#f3f4f6]',
  '[&_.typeahead-hint]:[color:#4b5563]',
  '[&_.typeahead-hint]:[font-size:12px]',
  '[&_.typeahead-name::first-letter]:[text-transform:uppercase]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
