// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Article comments',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="comments-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(EmojiPicker)`
  --epr-bg-color: #ffffff;
  --epr-reactions-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #0f766e;
  --epr-hover-bg-color: #f0fdfa;
  --epr-hover-bg-color-reduced-opacity: #f0fdfa;
  --epr-focus-bg-color: #ccfbf1;
  --epr-picker-border-color: #e5e7eb;
  --epr-search-border-color-active: #14b8a6;
  --epr-category-icon-active-color: #0f766e;
  --epr-category-label-text-color: #4b5563;
  --epr-picker-border-radius: 14px;
  box-shadow: 0 10px 30px rgb(17 24 39 / 12%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='reaction'] {
    border-radius: 10px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    text-transform: none;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(EmojiPicker)`
  --epr-bg-color: #ffffff;
  --epr-reactions-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #0f766e;
  --epr-hover-bg-color: #f0fdfa;
  --epr-hover-bg-color-reduced-opacity: #f0fdfa;
  --epr-focus-bg-color: #ccfbf1;
  --epr-picker-border-color: #e5e7eb;
  --epr-search-border-color-active: #14b8a6;
  --epr-category-icon-active-color: #0f766e;
  --epr-category-label-text-color: #4b5563;
  --epr-picker-border-radius: 14px;
  box-shadow: 0 10px 30px rgb(17 24 39 / 12%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='reaction'] {
    border-radius: 10px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    text-transform: none;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(EmojiPicker)({
  "--epr-bg-color": "#ffffff",
  "--epr-reactions-bg-color": "#ffffff",
  "--epr-text-color": "#4b5563",
  "--epr-highlight-color": "#0f766e",
  "--epr-hover-bg-color": "#f0fdfa",
  "--epr-hover-bg-color-reduced-opacity": "#f0fdfa",
  "--epr-focus-bg-color": "#ccfbf1",
  "--epr-picker-border-color": "#e5e7eb",
  "--epr-search-border-color-active": "#14b8a6",
  "--epr-category-icon-active-color": "#0f766e",
  "--epr-category-label-text-color": "#4b5563",
  "--epr-picker-border-radius": "14px",
  boxShadow: "0 10px 30px rgb(17 24 39 / 12%)",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='reaction']": {
    borderRadius: "10px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "13px",
    textTransform: "none",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof EmojiPicker>) => (
  <EmojiPicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-text-color:#4b5563]',
  '[--epr-highlight-color:#0f766e]',
  '[--epr-hover-bg-color:#f0fdfa]',
  '[--epr-hover-bg-color-reduced-opacity:#f0fdfa]',
  '[--epr-focus-bg-color:#ccfbf1]',
  '[--epr-picker-border-color:#e5e7eb]',
  '[--epr-search-border-color-active:#14b8a6]',
  '[--epr-category-icon-active-color:#0f766e]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-picker-border-radius:14px]',
  '[box-shadow:0_10px_30px_rgb(17_24_39_/_12%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=reaction]]:[border-radius:10px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#4b5563",
  "--primary": "#0f766e",
  "--accent": "#f0fdfa",
  "--border": "#e5e7eb",
  "--ring": "#14b8a6"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-hover-bg-color-reduced-opacity:#f0fdfa]',
  '[--epr-focus-bg-color:#ccfbf1]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-category-icon-active-color:#0f766e]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-picker-border-radius:14px]',
  '[box-shadow:0_10px_30px_rgb(17_24_39_/_12%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=reaction]]:[border-radius:10px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
