// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Slack reactions',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="slack-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(EmojiPicker)`
  --epr-bg-color: #ffffff;
  --epr-reactions-bg-color: #ffffff;
  --epr-text-color: #1d1c1d;
  --epr-highlight-color: #1264a3;
  --epr-hover-bg-color: #f8f8f8;
  --epr-focus-bg-color: #e8f5fa;
  --epr-picker-border-color: #dddddd;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-border-color: #868686;
  --epr-search-border-color-active: #1264a3;
  --epr-category-icon-active-color: #1264a3;
  --epr-category-label-text-color: #616061;
  --epr-category-label-bg-color: #ffffffee;
  --epr-picker-border-radius: 8px;
  margin-left: 46px;
  box-shadow: 0 4px 12px rgb(0 0 0 / 12%);
  font-family: inherit;

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 700;
    text-transform: none;
  }

  & [data-epr-part='reactions'] {
    padding: 0 6px;
  }

  & [data-epr-part='reaction'] {
    border-radius: 6px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(EmojiPicker)`
  --epr-bg-color: #ffffff;
  --epr-reactions-bg-color: #ffffff;
  --epr-text-color: #1d1c1d;
  --epr-highlight-color: #1264a3;
  --epr-hover-bg-color: #f8f8f8;
  --epr-focus-bg-color: #e8f5fa;
  --epr-picker-border-color: #dddddd;
  --epr-search-input-bg-color: #ffffff;
  --epr-search-border-color: #868686;
  --epr-search-border-color-active: #1264a3;
  --epr-category-icon-active-color: #1264a3;
  --epr-category-label-text-color: #616061;
  --epr-category-label-bg-color: #ffffffee;
  --epr-picker-border-radius: 8px;
  margin-left: 46px;
  box-shadow: 0 4px 12px rgb(0 0 0 / 12%);
  font-family: inherit;

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 700;
    text-transform: none;
  }

  & [data-epr-part='reactions'] {
    padding: 0 6px;
  }

  & [data-epr-part='reaction'] {
    border-radius: 6px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(EmojiPicker)({
  "--epr-bg-color": "#ffffff",
  "--epr-reactions-bg-color": "#ffffff",
  "--epr-text-color": "#1d1c1d",
  "--epr-highlight-color": "#1264a3",
  "--epr-hover-bg-color": "#f8f8f8",
  "--epr-focus-bg-color": "#e8f5fa",
  "--epr-picker-border-color": "#dddddd",
  "--epr-search-input-bg-color": "#ffffff",
  "--epr-search-border-color": "#868686",
  "--epr-search-border-color-active": "#1264a3",
  "--epr-category-icon-active-color": "#1264a3",
  "--epr-category-label-text-color": "#616061",
  "--epr-category-label-bg-color": "#ffffffee",
  "--epr-picker-border-radius": "8px",
  marginLeft: "46px",
  boxShadow: "0 4px 12px rgb(0 0 0 / 12%)",
  fontFamily: "inherit",
  "& [data-epr-part='category-label']": {
    fontSize: "13px",
    fontWeight: "700",
    textTransform: "none",
  },
  "& [data-epr-part='reactions']": {
    padding: "0 6px",
  },
  "& [data-epr-part='reaction']": {
    borderRadius: "6px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof EmojiPicker>) => (
  <EmojiPicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-text-color:#1d1c1d]',
  '[--epr-highlight-color:#1264a3]',
  '[--epr-hover-bg-color:#f8f8f8]',
  '[--epr-focus-bg-color:#e8f5fa]',
  '[--epr-picker-border-color:#dddddd]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-border-color:#868686]',
  '[--epr-search-border-color-active:#1264a3]',
  '[--epr-category-icon-active-color:#1264a3]',
  '[--epr-category-label-text-color:#616061]',
  '[--epr-category-label-bg-color:#ffffffee]',
  '[--epr-picker-border-radius:8px]',
  '[margin-left:46px]',
  '[box-shadow:0_4px_12px_rgb(0_0_0_/_12%)]',
  '[font-family:inherit]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=reactions]]:[padding:0_6px]',
  '[&_[data-epr-part=reaction]]:[border-radius:6px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#1d1c1d",
  "--primary": "#1264a3",
  "--accent": "#f8f8f8",
  "--border": "#dddddd",
  "--input": "#868686",
  "--ring": "#1264a3"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-reactions-bg-color:#ffffff]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e8f5fa]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-search-input-bg-color:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-category-icon-active-color:#1264a3]',
  '[--epr-category-label-text-color:#616061]',
  '[--epr-category-label-bg-color:#ffffffee]',
  '[--epr-picker-border-radius:8px]',
  '[margin-left:46px]',
  '[box-shadow:0_4px_12px_rgb(0_0_0_/_12%)]',
  '[font-family:inherit]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:700]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=reactions]]:[padding:0_6px]',
  '[&_[data-epr-part=reaction]]:[border-radius:6px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
