// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Doc editor insert panel',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="editor-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #4338ca;
  --epr-hover-bg-color: #eef2ff;
  --epr-focus-bg-color: #e0e7ff;
  --epr-search-input-bg-color: #f3f4f6;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #4338ca;
  --epr-search-input-height: 32px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #111827;
  --epr-search-input-placeholder-color: #6b7280;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #4b5563;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #4338ca;
  --epr-category-icon-inactive-color: #6b7280;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 10px;
  width: 520px;
  height: 330px;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & .editor-columns {
    display: flex;
    flex: 1;
    min-height: 0;
  }

  & [data-epr-part='category-nav'] {
    border-right: 1px solid #f3f4f6;
    background: #f9fafb;
    padding-left: 6px;
    padding-right: 6px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #e0e7ff;
  }

  & .editor-main {
    display: flex;
    flex: 1;
    flex-direction: column;
    min-width: 0;
  }

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & .editor-details {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 8px;
    width: 140px;
    padding: 12px;
    border-left: 1px solid #f3f4f6;
    text-align: center;
  }

  & .editor-details-glyph {
    font-size: 48px;
    line-height: 1;
  }

  & .editor-details-name {
    color: #111827;
    font-size: 13px;
    font-weight: 600;
    text-transform: capitalize;
  }

  & .editor-details-code {
    color: #4b5563;
    font-size: 11px;
    word-break: break-all;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #4b5563;
  --epr-highlight-color: #4338ca;
  --epr-hover-bg-color: #eef2ff;
  --epr-focus-bg-color: #e0e7ff;
  --epr-search-input-bg-color: #f3f4f6;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: #4338ca;
  --epr-search-input-height: 32px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #111827;
  --epr-search-input-placeholder-color: #6b7280;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #4b5563;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #4338ca;
  --epr-category-icon-inactive-color: #6b7280;
  --epr-category-navigation-button-size: 20px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 10px;
  width: 520px;
  height: 330px;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & .editor-columns {
    display: flex;
    flex: 1;
    min-height: 0;
  }

  & [data-epr-part='category-nav'] {
    border-right: 1px solid #f3f4f6;
    background: #f9fafb;
    padding-left: 6px;
    padding-right: 6px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #e0e7ff;
  }

  & .editor-main {
    display: flex;
    flex: 1;
    flex-direction: column;
    min-width: 0;
  }

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & .editor-details {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 8px;
    width: 140px;
    padding: 12px;
    border-left: 1px solid #f3f4f6;
    text-align: center;
  }

  & .editor-details-glyph {
    font-size: 48px;
    line-height: 1;
  }

  & .editor-details-name {
    color: #111827;
    font-size: 13px;
    font-weight: 600;
    text-transform: capitalize;
  }

  & .editor-details-code {
    color: #4b5563;
    font-size: 11px;
    word-break: break-all;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#4b5563",
  "--epr-highlight-color": "#4338ca",
  "--epr-hover-bg-color": "#eef2ff",
  "--epr-focus-bg-color": "#e0e7ff",
  "--epr-search-input-bg-color": "#f3f4f6",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "#4338ca",
  "--epr-search-input-height": "32px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-text-color": "#111827",
  "--epr-search-input-placeholder-color": "#6b7280",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#4b5563",
  "--epr-category-label-height": "28px",
  "--epr-category-icon-active-color": "#4338ca",
  "--epr-category-icon-inactive-color": "#6b7280",
  "--epr-category-navigation-button-size": "20px",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "10px",
  width: "520px",
  height: "330px",
  border: "1px solid #e5e7eb",
  borderRadius: "12px",
  background: "#ffffff",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& .editor-columns": {
    display: "flex",
    flex: "1",
    minHeight: "0",
  },
  "& [data-epr-part='category-nav']": {
    borderRight: "1px solid #f3f4f6",
    background: "#f9fafb",
    paddingLeft: "6px",
    paddingRight: "6px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    borderRadius: "6px",
    backgroundColor: "#e0e7ff",
  },
  "& .editor-main": {
    display: "flex",
    flex: "1",
    flexDirection: "column",
    minWidth: "0",
  },
  "& [data-epr-part='search'] > *": {
    padding: "10px 10px 4px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "6px",
  },
  "& .editor-details": {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    width: "140px",
    padding: "12px",
    borderLeft: "1px solid #f3f4f6",
    textAlign: "center",
  },
  "& .editor-details-glyph": {
    fontSize: "48px",
    lineHeight: "1",
  },
  "& .editor-details-name": {
    color: "#111827",
    fontSize: "13px",
    fontWeight: "600",
    textTransform: "capitalize",
  },
  "& .editor-details-code": {
    color: "#4b5563",
    fontSize: "11px",
    wordBreak: "break-all",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#4b5563]',
  '[--epr-highlight-color:#4338ca]',
  '[--epr-hover-bg-color:#eef2ff]',
  '[--epr-focus-bg-color:#e0e7ff]',
  '[--epr-search-input-bg-color:#f3f4f6]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:#4338ca]',
  '[--epr-search-input-height:32px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:#111827]',
  '[--epr-search-input-placeholder-color:#6b7280]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#4338ca]',
  '[--epr-category-icon-inactive-color:#6b7280]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:10px]',
  '[width:520px]',
  '[height:330px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_.editor-columns]:[display:flex]',
  '[&_.editor-columns]:[flex:1]',
  '[&_.editor-columns]:[min-height:0]',
  '[&_[data-epr-part=category-nav]]:[border-right:1px_solid_#f3f4f6]',
  '[&_[data-epr-part=category-nav]]:[background:#f9fafb]',
  '[&_[data-epr-part=category-nav]]:[padding-left:6px]',
  '[&_[data-epr-part=category-nav]]:[padding-right:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#e0e7ff]',
  '[&_.editor-main]:[display:flex]',
  '[&_.editor-main]:[flex:1]',
  '[&_.editor-main]:[flex-direction:column]',
  '[&_.editor-main]:[min-width:0]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_.editor-details]:[display:flex]',
  '[&_.editor-details]:[flex-direction:column]',
  '[&_.editor-details]:[align-items:center]',
  '[&_.editor-details]:[justify-content:center]',
  '[&_.editor-details]:[gap:8px]',
  '[&_.editor-details]:[width:140px]',
  '[&_.editor-details]:[padding:12px]',
  '[&_.editor-details]:[border-left:1px_solid_#f3f4f6]',
  '[&_.editor-details]:[text-align:center]',
  '[&_.editor-details-glyph]:[font-size:48px]',
  '[&_.editor-details-glyph]:[line-height:1]',
  '[&_.editor-details-name]:[color:#111827]',
  '[&_.editor-details-name]:[font-size:13px]',
  '[&_.editor-details-name]:[font-weight:600]',
  '[&_.editor-details-name]:[text-transform:capitalize]',
  '[&_.editor-details-code]:[color:#4b5563]',
  '[&_.editor-details-code]:[font-size:11px]',
  '[&_.editor-details-code]:[word-break:break-all]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#4b5563",
  "--primary": "#4338ca",
  "--accent": "#eef2ff",
  "--input": "transparent",
  "--ring": "#4338ca",
  "--popover-foreground": "#111827"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e0e7ff]',
  '[--epr-search-input-bg-color:#f3f4f6]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:32px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#6b7280]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#4b5563]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#4338ca]',
  '[--epr-category-icon-inactive-color:#6b7280]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:10px]',
  '[width:520px]',
  '[height:330px]',
  '[border:1px_solid_#e5e7eb]',
  '[border-radius:12px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_.editor-columns]:[display:flex]',
  '[&_.editor-columns]:[flex:1]',
  '[&_.editor-columns]:[min-height:0]',
  '[&_[data-epr-part=category-nav]]:[border-right:1px_solid_#f3f4f6]',
  '[&_[data-epr-part=category-nav]]:[background:#f9fafb]',
  '[&_[data-epr-part=category-nav]]:[padding-left:6px]',
  '[&_[data-epr-part=category-nav]]:[padding-right:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#e0e7ff]',
  '[&_.editor-main]:[display:flex]',
  '[&_.editor-main]:[flex:1]',
  '[&_.editor-main]:[flex-direction:column]',
  '[&_.editor-main]:[min-width:0]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_.editor-details]:[display:flex]',
  '[&_.editor-details]:[flex-direction:column]',
  '[&_.editor-details]:[align-items:center]',
  '[&_.editor-details]:[justify-content:center]',
  '[&_.editor-details]:[gap:8px]',
  '[&_.editor-details]:[width:140px]',
  '[&_.editor-details]:[padding:12px]',
  '[&_.editor-details]:[border-left:1px_solid_#f3f4f6]',
  '[&_.editor-details]:[text-align:center]',
  '[&_.editor-details-glyph]:[font-size:48px]',
  '[&_.editor-details-glyph]:[line-height:1]',
  '[&_.editor-details-name]:[color:#111827]',
  '[&_.editor-details-name]:[font-size:13px]',
  '[&_.editor-details-name]:[font-weight:600]',
  '[&_.editor-details-name]:[text-transform:capitalize]',
  '[&_.editor-details-code]:[color:#4b5563]',
  '[&_.editor-details-code]:[font-size:11px]',
  '[&_.editor-details-code]:[word-break:break-all]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
