// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Material 3',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="m3-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --m3-primary: #6750a4;
  --m3-on-surface: #1d1b20;
  --m3-on-surface-variant: #49454f;
  --m3-surface: #f7f2fa;
  --m3-surface-container: #ece6f0;
  --m3-secondary-container: #e8def8;
  --epr-bg-color: var(--m3-surface);
  --epr-text-color: var(--m3-on-surface-variant);
  --epr-highlight-color: var(--m3-primary);
  --epr-hover-bg-color: rgb(103 80 164 / 8%);
  --epr-focus-bg-color: rgb(103 80 164 / 12%);
  --epr-search-input-bg-color: var(--m3-surface-container);
  --epr-search-input-bg-color-active: var(--m3-surface-container);
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 48px;
  --epr-search-input-border-radius: 28px;
  --epr-search-input-padding: 0 20px 0 48px;
  --epr-search-input-text-color: var(--m3-on-surface);
  --epr-search-input-placeholder-color: var(--m3-on-surface-variant);
  --epr-category-label-bg-color: rgb(247 242 250 / 94%);
  --epr-category-label-text-color: var(--m3-primary);
  --epr-category-label-height: 36px;
  --epr-category-icon-active-color: #21005d;
  --epr-category-icon-inactive-color: var(--m3-on-surface-variant);
  --epr-category-navigation-button-size: 24px;
  --epr-emoji-variation-picker-bg-color: var(--m3-surface-container);
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  width: 380px;
  height: 480px;
  border-radius: 28px;
  background: var(--m3-surface);
  box-shadow: 0 1px 3px rgb(0 0 0 / 30%), 0 4px 8px 3px rgb(0 0 0 / 15%);
  font-family: Roboto, 'Google Sans', 'Segoe UI', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 16px 16px 8px;
  }

  & [data-epr-part='category-label'] {
    font-size: 14px;
    font-weight: 500;
    letter-spacing: 0.1px;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-nav'] {
    background: var(--m3-surface-container);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 12px 8px 14px;
  }

  & [data-epr-part='category-tab'] {
    width: 36px;
    border-radius: 16px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    background-color: var(--m3-secondary-container);
  }

  & [data-epr-part='category-tab']:focus::before {
    border-radius: 16px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --m3-primary: #6750a4;
  --m3-on-surface: #1d1b20;
  --m3-on-surface-variant: #49454f;
  --m3-surface: #f7f2fa;
  --m3-surface-container: #ece6f0;
  --m3-secondary-container: #e8def8;
  --epr-bg-color: var(--m3-surface);
  --epr-text-color: var(--m3-on-surface-variant);
  --epr-highlight-color: var(--m3-primary);
  --epr-hover-bg-color: rgb(103 80 164 / 8%);
  --epr-focus-bg-color: rgb(103 80 164 / 12%);
  --epr-search-input-bg-color: var(--m3-surface-container);
  --epr-search-input-bg-color-active: var(--m3-surface-container);
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 48px;
  --epr-search-input-border-radius: 28px;
  --epr-search-input-padding: 0 20px 0 48px;
  --epr-search-input-text-color: var(--m3-on-surface);
  --epr-search-input-placeholder-color: var(--m3-on-surface-variant);
  --epr-category-label-bg-color: rgb(247 242 250 / 94%);
  --epr-category-label-text-color: var(--m3-primary);
  --epr-category-label-height: 36px;
  --epr-category-icon-active-color: #21005d;
  --epr-category-icon-inactive-color: var(--m3-on-surface-variant);
  --epr-category-navigation-button-size: 24px;
  --epr-emoji-variation-picker-bg-color: var(--m3-surface-container);
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  width: 380px;
  height: 480px;
  border-radius: 28px;
  background: var(--m3-surface);
  box-shadow: 0 1px 3px rgb(0 0 0 / 30%), 0 4px 8px 3px rgb(0 0 0 / 15%);
  font-family: Roboto, 'Google Sans', 'Segoe UI', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 16px 16px 8px;
  }

  & [data-epr-part='category-label'] {
    font-size: 14px;
    font-weight: 500;
    letter-spacing: 0.1px;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-nav'] {
    background: var(--m3-surface-container);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 12px 8px 14px;
  }

  & [data-epr-part='category-tab'] {
    width: 36px;
    border-radius: 16px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    background-color: var(--m3-secondary-container);
  }

  & [data-epr-part='category-tab']:focus::before {
    border-radius: 16px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--m3-primary": "#6750a4",
  "--m3-on-surface": "#1d1b20",
  "--m3-on-surface-variant": "#49454f",
  "--m3-surface": "#f7f2fa",
  "--m3-surface-container": "#ece6f0",
  "--m3-secondary-container": "#e8def8",
  "--epr-bg-color": "var(--m3-surface)",
  "--epr-text-color": "var(--m3-on-surface-variant)",
  "--epr-highlight-color": "var(--m3-primary)",
  "--epr-hover-bg-color": "rgb(103 80 164 / 8%)",
  "--epr-focus-bg-color": "rgb(103 80 164 / 12%)",
  "--epr-search-input-bg-color": "var(--m3-surface-container)",
  "--epr-search-input-bg-color-active": "var(--m3-surface-container)",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "transparent",
  "--epr-search-input-height": "48px",
  "--epr-search-input-border-radius": "28px",
  "--epr-search-input-padding": "0 20px 0 48px",
  "--epr-search-input-text-color": "var(--m3-on-surface)",
  "--epr-search-input-placeholder-color": "var(--m3-on-surface-variant)",
  "--epr-category-label-bg-color": "rgb(247 242 250 / 94%)",
  "--epr-category-label-text-color": "var(--m3-primary)",
  "--epr-category-label-height": "36px",
  "--epr-category-icon-active-color": "#21005d",
  "--epr-category-icon-inactive-color": "var(--m3-on-surface-variant)",
  "--epr-category-navigation-button-size": "24px",
  "--epr-emoji-variation-picker-bg-color": "var(--m3-surface-container)",
  "--epr-emoji-size": "30px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "16px",
  width: "380px",
  height: "480px",
  borderRadius: "28px",
  background: "var(--m3-surface)",
  boxShadow: "0 1px 3px rgb(0 0 0 / 30%), 0 4px 8px 3px rgb(0 0 0 / 15%)",
  fontFamily: "Roboto, 'Google Sans', 'Segoe UI', Arial, sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "16px 16px 8px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "14px",
    fontWeight: "500",
    letterSpacing: "0.1px",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "50%",
  },
  "& [data-epr-part='category-nav']": {
    background: "var(--m3-surface-container)",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "12px 8px 14px",
  },
  "& [data-epr-part='category-tab']": {
    width: "36px",
    borderRadius: "16px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    backgroundColor: "var(--m3-secondary-container)",
  },
  "& [data-epr-part='category-tab']:focus::before": {
    borderRadius: "16px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--m3-primary:#6750a4]',
  '[--m3-on-surface:#1d1b20]',
  '[--m3-on-surface-variant:#49454f]',
  '[--m3-surface:#f7f2fa]',
  '[--m3-surface-container:#ece6f0]',
  '[--m3-secondary-container:#e8def8]',
  '[--epr-bg-color:var(--m3-surface)]',
  '[--epr-text-color:var(--m3-on-surface-variant)]',
  '[--epr-highlight-color:var(--m3-primary)]',
  '[--epr-hover-bg-color:rgb(103_80_164_/_8%)]',
  '[--epr-focus-bg-color:rgb(103_80_164_/_12%)]',
  '[--epr-search-input-bg-color:var(--m3-surface-container)]',
  '[--epr-search-input-bg-color-active:var(--m3-surface-container)]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:transparent]',
  '[--epr-search-input-height:48px]',
  '[--epr-search-input-border-radius:28px]',
  '[--epr-search-input-padding:0_20px_0_48px]',
  '[--epr-search-input-text-color:var(--m3-on-surface)]',
  '[--epr-search-input-placeholder-color:var(--m3-on-surface-variant)]',
  '[--epr-category-label-bg-color:rgb(247_242_250_/_94%)]',
  '[--epr-category-label-text-color:var(--m3-primary)]',
  '[--epr-category-label-height:36px]',
  '[--epr-category-icon-active-color:#21005d]',
  '[--epr-category-icon-inactive-color:var(--m3-on-surface-variant)]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-emoji-variation-picker-bg-color:var(--m3-surface-container)]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[width:380px]',
  '[height:480px]',
  '[border-radius:28px]',
  '[background:var(--m3-surface)]',
  '[box-shadow:0_1px_3px_rgb(0_0_0_/_30%),_0_4px_8px_3px_rgb(0_0_0_/_15%)]',
  "[font-family:Roboto,_'Google_Sans',_'Segoe_UI',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:16px_16px_8px]',
  '[&_[data-epr-part=category-label]]:[font-size:14px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.1px]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
  '[&_[data-epr-part=category-nav]]:[background:var(--m3-surface-container)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:12px_8px_14px]',
  '[&_[data-epr-part=category-tab]]:[width:36px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:16px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:var(--m3-secondary-container)]',
  '[&_[data-epr-part=category-tab]:focus::before]:[border-radius:16px]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--accent": "rgb(103 80 164 / 8%)",
  "--input": "transparent",
  "--ring": "transparent"
} as React.CSSProperties;

const shadcn = [
  '[--m3-primary:#6750a4]',
  '[--m3-on-surface:#1d1b20]',
  '[--m3-on-surface-variant:#49454f]',
  '[--m3-surface:#f7f2fa]',
  '[--m3-surface-container:#ece6f0]',
  '[--m3-secondary-container:#e8def8]',
  '[--epr-bg-color:var(--m3-surface)]',
  '[--epr-text-color:var(--m3-on-surface-variant)]',
  '[--epr-highlight-color:var(--m3-primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:rgb(103_80_164_/_12%)]',
  '[--epr-search-input-bg-color:var(--m3-surface-container)]',
  '[--epr-search-input-bg-color-active:var(--m3-surface-container)]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:48px]',
  '[--epr-search-input-border-radius:28px]',
  '[--epr-search-input-padding:0_20px_0_48px]',
  '[--epr-search-input-text-color:var(--m3-on-surface)]',
  '[--epr-search-input-placeholder-color:var(--m3-on-surface-variant)]',
  '[--epr-category-label-bg-color:rgb(247_242_250_/_94%)]',
  '[--epr-category-label-text-color:var(--m3-primary)]',
  '[--epr-category-label-height:36px]',
  '[--epr-category-icon-active-color:#21005d]',
  '[--epr-category-icon-inactive-color:var(--m3-on-surface-variant)]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-emoji-variation-picker-bg-color:var(--m3-surface-container)]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[width:380px]',
  '[height:480px]',
  '[border-radius:28px]',
  '[background:var(--m3-surface)]',
  '[box-shadow:0_1px_3px_rgb(0_0_0_/_30%),_0_4px_8px_3px_rgb(0_0_0_/_15%)]',
  "[font-family:Roboto,_'Google_Sans',_'Segoe_UI',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:16px_16px_8px]',
  '[&_[data-epr-part=category-label]]:[font-size:14px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.1px]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
  '[&_[data-epr-part=category-nav]]:[background:var(--m3-surface-container)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:12px_8px_14px]',
  '[&_[data-epr-part=category-tab]]:[width:36px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:16px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:var(--m3-secondary-container)]',
  '[&_[data-epr-part=category-tab]:focus::before]:[border-radius:16px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
