// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Linear command palette',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="linear-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #1b1b1f;
  --epr-text-color: #e3e4e8;
  --epr-highlight-color: #8b8ff8;
  --epr-hover-bg-color: #2b2c33;
  --epr-focus-bg-color: #33343c;
  --epr-search-input-bg-color: transparent;
  --epr-search-input-bg-color-active: transparent;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 52px;
  --epr-search-input-padding: 0 16px 0 44px;
  --epr-search-input-text-color: #f7f8f8;
  --epr-search-input-placeholder-color: #6b6f76;
  --epr-category-label-bg-color: #1b1b1fee;
  --epr-category-label-text-color: #8a8f98;
  --epr-category-label-height: 28px;
  --epr-emoji-variation-picker-bg-color: #26272d;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 12px;
  width: 560px;
  height: 380px;
  border: 1px solid #2e2f36;
  border-radius: 12px;
  background: var(--epr-bg-color);
  box-shadow: 0 24px 60px rgb(0 0 0 / 55%);
  font-family: Inter, 'SF Pro Display', -apple-system, 'Segoe UI', sans-serif;
  color: var(--epr-text-color);

  & [data-epr-part='search'] {
    border-bottom: 1px solid #2e2f36;
  }

  & [data-epr-part='search'] input {
    font-size: 17px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 500;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & [data-epr-part='search'] > * {
    padding: 0 4px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #1b1b1f;
  --epr-text-color: #e3e4e8;
  --epr-highlight-color: #8b8ff8;
  --epr-hover-bg-color: #2b2c33;
  --epr-focus-bg-color: #33343c;
  --epr-search-input-bg-color: transparent;
  --epr-search-input-bg-color-active: transparent;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 52px;
  --epr-search-input-padding: 0 16px 0 44px;
  --epr-search-input-text-color: #f7f8f8;
  --epr-search-input-placeholder-color: #6b6f76;
  --epr-category-label-bg-color: #1b1b1fee;
  --epr-category-label-text-color: #8a8f98;
  --epr-category-label-height: 28px;
  --epr-emoji-variation-picker-bg-color: #26272d;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 12px;
  width: 560px;
  height: 380px;
  border: 1px solid #2e2f36;
  border-radius: 12px;
  background: var(--epr-bg-color);
  box-shadow: 0 24px 60px rgb(0 0 0 / 55%);
  font-family: Inter, 'SF Pro Display', -apple-system, 'Segoe UI', sans-serif;
  color: var(--epr-text-color);

  & [data-epr-part='search'] {
    border-bottom: 1px solid #2e2f36;
  }

  & [data-epr-part='search'] input {
    font-size: 17px;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 500;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 6px;
  }

  & [data-epr-part='search'] > * {
    padding: 0 4px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#1b1b1f",
  "--epr-text-color": "#e3e4e8",
  "--epr-highlight-color": "#8b8ff8",
  "--epr-hover-bg-color": "#2b2c33",
  "--epr-focus-bg-color": "#33343c",
  "--epr-search-input-bg-color": "transparent",
  "--epr-search-input-bg-color-active": "transparent",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "transparent",
  "--epr-search-input-height": "52px",
  "--epr-search-input-padding": "0 16px 0 44px",
  "--epr-search-input-text-color": "#f7f8f8",
  "--epr-search-input-placeholder-color": "#6b6f76",
  "--epr-category-label-bg-color": "#1b1b1fee",
  "--epr-category-label-text-color": "#8a8f98",
  "--epr-category-label-height": "28px",
  "--epr-emoji-variation-picker-bg-color": "#26272d",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "12px",
  width: "560px",
  height: "380px",
  border: "1px solid #2e2f36",
  borderRadius: "12px",
  background: "var(--epr-bg-color)",
  boxShadow: "0 24px 60px rgb(0 0 0 / 55%)",
  fontFamily: "Inter, 'SF Pro Display', -apple-system, 'Segoe UI', sans-serif",
  color: "var(--epr-text-color)",
  "& [data-epr-part='search']": {
    borderBottom: "1px solid #2e2f36",
  },
  "& [data-epr-part='search'] input": {
    fontSize: "17px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "500",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "6px",
  },
  "& [data-epr-part='search'] > *": {
    padding: "0 4px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#1b1b1f]',
  '[--epr-text-color:#e3e4e8]',
  '[--epr-highlight-color:#8b8ff8]',
  '[--epr-hover-bg-color:#2b2c33]',
  '[--epr-focus-bg-color:#33343c]',
  '[--epr-search-input-bg-color:transparent]',
  '[--epr-search-input-bg-color-active:transparent]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:transparent]',
  '[--epr-search-input-height:52px]',
  '[--epr-search-input-padding:0_16px_0_44px]',
  '[--epr-search-input-text-color:#f7f8f8]',
  '[--epr-search-input-placeholder-color:#6b6f76]',
  '[--epr-category-label-bg-color:#1b1b1fee]',
  '[--epr-category-label-text-color:#8a8f98]',
  '[--epr-category-label-height:28px]',
  '[--epr-emoji-variation-picker-bg-color:#26272d]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:12px]',
  '[width:560px]',
  '[height:380px]',
  '[border:1px_solid_#2e2f36]',
  '[border-radius:12px]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_24px_60px_rgb(0_0_0_/_55%)]',
  "[font-family:Inter,_'SF_Pro_Display',_-apple-system,_'Segoe_UI',_sans-serif]",
  '[color:var(--epr-text-color)]',
  '[&_[data-epr-part=search]]:[border-bottom:1px_solid_#2e2f36]',
  '[&_[data-epr-part=search]_input]:[font-size:17px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_[data-epr-part=search]_>_*]:[padding:0_4px]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#1b1b1f",
  "--muted-foreground": "#e3e4e8",
  "--primary": "#8b8ff8",
  "--accent": "#2b2c33",
  "--input": "transparent",
  "--ring": "transparent",
  "--popover-foreground": "#f7f8f8"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#33343c]',
  '[--epr-search-input-bg-color:transparent]',
  '[--epr-search-input-bg-color-active:transparent]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:52px]',
  '[--epr-search-input-padding:0_16px_0_44px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#6b6f76]',
  '[--epr-category-label-bg-color:#1b1b1fee]',
  '[--epr-category-label-text-color:#8a8f98]',
  '[--epr-category-label-height:28px]',
  '[--epr-emoji-variation-picker-bg-color:#26272d]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:12px]',
  '[width:560px]',
  '[height:380px]',
  '[border:1px_solid_#2e2f36]',
  '[border-radius:12px]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_24px_60px_rgb(0_0_0_/_55%)]',
  "[font-family:Inter,_'SF_Pro_Display',_-apple-system,_'Segoe_UI',_sans-serif]",
  '[color:var(--epr-text-color)]',
  '[&_[data-epr-part=search]]:[border-bottom:1px_solid_#2e2f36]',
  '[&_[data-epr-part=search]_input]:[font-size:17px]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:6px]',
  '[&_[data-epr-part=search]_>_*]:[padding:0_4px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
