// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/WhatsApp keyboard panel',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="wa-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #54656f;
  --epr-highlight-color: #00a884;
  --epr-hover-bg-color: #f5f6f6;
  --epr-focus-bg-color: #e9edef;
  --epr-search-input-bg-color: #f0f2f5;
  --epr-search-input-bg-color-active: #f0f2f5;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-padding: 0 12px 0 36px;
  --epr-search-input-text-color: #111b21;
  --epr-search-input-placeholder-color: #667781;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #667781;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #00a884;
  --epr-category-icon-inactive-color: #8696a0;
  --epr-category-navigation-button-size: 24px;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  width: 100%;
  height: 300px;
  border-top: 1px solid #e9edef;
  background: #fff;

  & [data-epr-part='search'] > * {
    padding: 10px 16px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 500;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-nav'] {
    border-top: 1px solid #e9edef;
  }

  & [data-epr-part='category-nav'] > * {
    justify-content: space-between;
    padding: 6px 40px;
  }

  & [data-epr-part='category-tab'][aria-selected='true']::after {
    content: '';
    position: absolute;
    right: -10px;
    bottom: -6px;
    left: -10px;
    height: 3px;
    border-radius: 3px 3px 0 0;
    background: #00a884;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #54656f;
  --epr-highlight-color: #00a884;
  --epr-hover-bg-color: #f5f6f6;
  --epr-focus-bg-color: #e9edef;
  --epr-search-input-bg-color: #f0f2f5;
  --epr-search-input-bg-color-active: #f0f2f5;
  --epr-search-border-color: transparent;
  --epr-search-border-color-active: transparent;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-padding: 0 12px 0 36px;
  --epr-search-input-text-color: #111b21;
  --epr-search-input-placeholder-color: #667781;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #667781;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #00a884;
  --epr-category-icon-inactive-color: #8696a0;
  --epr-category-navigation-button-size: 24px;
  --epr-emoji-size: 30px;
  --epr-emoji-padding: 6px;
  --epr-horizontal-padding: 16px;
  width: 100%;
  height: 300px;
  border-top: 1px solid #e9edef;
  background: #fff;

  & [data-epr-part='search'] > * {
    padding: 10px 16px 4px;
  }

  & [data-epr-part='category-label'] {
    font-size: 13px;
    font-weight: 500;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }

  & [data-epr-part='category-nav'] {
    border-top: 1px solid #e9edef;
  }

  & [data-epr-part='category-nav'] > * {
    justify-content: space-between;
    padding: 6px 40px;
  }

  & [data-epr-part='category-tab'][aria-selected='true']::after {
    content: '';
    position: absolute;
    right: -10px;
    bottom: -6px;
    left: -10px;
    height: 3px;
    border-radius: 3px 3px 0 0;
    background: #00a884;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#54656f",
  "--epr-highlight-color": "#00a884",
  "--epr-hover-bg-color": "#f5f6f6",
  "--epr-focus-bg-color": "#e9edef",
  "--epr-search-input-bg-color": "#f0f2f5",
  "--epr-search-input-bg-color-active": "#f0f2f5",
  "--epr-search-border-color": "transparent",
  "--epr-search-border-color-active": "transparent",
  "--epr-search-input-height": "34px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-padding": "0 12px 0 36px",
  "--epr-search-input-text-color": "#111b21",
  "--epr-search-input-placeholder-color": "#667781",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#667781",
  "--epr-category-label-height": "28px",
  "--epr-category-icon-active-color": "#00a884",
  "--epr-category-icon-inactive-color": "#8696a0",
  "--epr-category-navigation-button-size": "24px",
  "--epr-emoji-size": "30px",
  "--epr-emoji-padding": "6px",
  "--epr-horizontal-padding": "16px",
  width: "100%",
  height: "300px",
  borderTop: "1px solid #e9edef",
  background: "#fff",
  "& [data-epr-part='search'] > *": {
    padding: "10px 16px 4px",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "13px",
    fontWeight: "500",
    textTransform: "uppercase",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "50%",
  },
  "& [data-epr-part='category-nav']": {
    borderTop: "1px solid #e9edef",
  },
  "& [data-epr-part='category-nav'] > *": {
    justifyContent: "space-between",
    padding: "6px 40px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']::after": {
    content: "''",
    position: "absolute",
    right: "-10px",
    bottom: "-6px",
    left: "-10px",
    height: "3px",
    borderRadius: "3px 3px 0 0",
    background: "#00a884",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#54656f]',
  '[--epr-highlight-color:#00a884]',
  '[--epr-hover-bg-color:#f5f6f6]',
  '[--epr-focus-bg-color:#e9edef]',
  '[--epr-search-input-bg-color:#f0f2f5]',
  '[--epr-search-input-bg-color-active:#f0f2f5]',
  '[--epr-search-border-color:transparent]',
  '[--epr-search-border-color-active:transparent]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-padding:0_12px_0_36px]',
  '[--epr-search-input-text-color:#111b21]',
  '[--epr-search-input-placeholder-color:#667781]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#667781]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#00a884]',
  '[--epr-category-icon-inactive-color:#8696a0]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[width:100%]',
  '[height:300px]',
  '[border-top:1px_solid_#e9edef]',
  '[background:#fff]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_16px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
  '[&_[data-epr-part=category-nav]]:[border-top:1px_solid_#e9edef]',
  '[&_[data-epr-part=category-nav]_>_*]:[justify-content:space-between]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_40px]',
  "[&_[data-epr-part=category-tab][aria-selected=true]::after]:[content:'']",
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[position:absolute]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[right:-10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[bottom:-6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[left:-10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[height:3px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[border-radius:3px_3px_0_0]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[background:#00a884]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#54656f",
  "--primary": "#00a884",
  "--accent": "#f5f6f6",
  "--input": "transparent",
  "--ring": "transparent",
  "--popover-foreground": "#111b21"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e9edef]',
  '[--epr-search-input-bg-color:#f0f2f5]',
  '[--epr-search-input-bg-color-active:#f0f2f5]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-padding:0_12px_0_36px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#667781]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#667781]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#00a884]',
  '[--epr-category-icon-inactive-color:#8696a0]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-emoji-size:30px]',
  '[--epr-emoji-padding:6px]',
  '[--epr-horizontal-padding:16px]',
  '[width:100%]',
  '[height:300px]',
  '[border-top:1px_solid_#e9edef]',
  '[background:#fff]',
  '[&_[data-epr-part=search]_>_*]:[padding:10px_16px_4px]',
  '[&_[data-epr-part=category-label]]:[font-size:13px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
  '[&_[data-epr-part=category-nav]]:[border-top:1px_solid_#e9edef]',
  '[&_[data-epr-part=category-nav]_>_*]:[justify-content:space-between]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_40px]',
  "[&_[data-epr-part=category-tab][aria-selected=true]::after]:[content:'']",
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[position:absolute]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[right:-10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[bottom:-6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[left:-10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[height:3px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[border-radius:3px_3px_0_0]',
  '[&_[data-epr-part=category-tab][aria-selected=true]::after]:[background:#00a884]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
