// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import EmojiPicker from '../../../src';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

// Styling libraries own their object-valued theme. Use colorScheme for the picker.
function RecipePicker({ theme, ...props }: Omit<React.ComponentProps<typeof EmojiPicker>, 'theme'> & { theme?: unknown }) {
  void theme;
  return <EmojiPicker {...props} />;
}

const meta = {
  title: 'Recipes/Examples/Video call reactions',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="call-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(RecipePicker)`
  --epr-reactions-bg-color: rgb(32 33 36 / 82%);
  --epr-picker-border-color: rgb(255 255 255 / 14%);
  --epr-hover-bg-color-reduced-opacity: rgb(255 255 255 / 16%);
  --epr-emoji-size: 32px;
  box-shadow: 0 12px 30px rgb(0 0 0 / 45%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='reactions'] {
    gap: 2px;
    padding: 0 8px;
  }

  & [data-epr-part='expand-reactions'] {
    background-color: rgb(255 255 255 / 12%);
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(RecipePicker)`
  --epr-reactions-bg-color: rgb(32 33 36 / 82%);
  --epr-picker-border-color: rgb(255 255 255 / 14%);
  --epr-hover-bg-color-reduced-opacity: rgb(255 255 255 / 16%);
  --epr-emoji-size: 32px;
  box-shadow: 0 12px 30px rgb(0 0 0 / 45%);
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='reactions'] {
    gap: 2px;
    padding: 0 8px;
  }

  & [data-epr-part='expand-reactions'] {
    background-color: rgb(255 255 255 / 12%);
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(RecipePicker)({
  "--epr-reactions-bg-color": "rgb(32 33 36 / 82%)",
  "--epr-picker-border-color": "rgb(255 255 255 / 14%)",
  "--epr-hover-bg-color-reduced-opacity": "rgb(255 255 255 / 16%)",
  "--epr-emoji-size": "32px",
  boxShadow: "0 12px 30px rgb(0 0 0 / 45%)",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='reactions']": {
    gap: "2px",
    padding: "0 8px",
  },
  "& [data-epr-part='expand-reactions']": {
    backgroundColor: "rgb(255 255 255 / 12%)",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof RecipePicker>) => (
  <RecipePicker cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-reactions-bg-color:rgb(32_33_36_/_82%)]',
  '[--epr-picker-border-color:rgb(255_255_255_/_14%)]',
  '[--epr-hover-bg-color-reduced-opacity:rgb(255_255_255_/_16%)]',
  '[--epr-emoji-size:32px]',
  '[box-shadow:0_12px_30px_rgb(0_0_0_/_45%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=reactions]]:[gap:2px]',
  '[&_[data-epr-part=reactions]]:[padding:0_8px]',
  '[&_[data-epr-part=expand-reactions]]:[background-color:rgb(255_255_255_/_12%)]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--border": "rgb(255 255 255 / 14%)"
} as React.CSSProperties;

const shadcn = [
  '[--epr-reactions-bg-color:rgb(32_33_36_/_82%)]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-hover-bg-color-reduced-opacity:rgb(255_255_255_/_16%)]',
  '[--epr-emoji-size:32px]',
  '[box-shadow:0_12px_30px_rgb(0_0_0_/_45%)]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=reactions]]:[gap:2px]',
  '[&_[data-epr-part=reactions]]:[padding:0_8px]',
  '[&_[data-epr-part=expand-reactions]]:[background-color:rgb(255_255_255_/_12%)]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
