// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Windows 95',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="w95-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #000000;
  --epr-category-label-height: 22px;
  --epr-category-icon-active-color: #000000;
  --epr-category-icon-inactive-color: #404040;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-variation-picker-bg-color: var(--w95-face);
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 6px;
  height: 360px;
  margin-top: 3px;
  background: var(--w95-face);

  & [data-epr-part='category-nav'] > * {
    justify-content: flex-start;
    gap: 2px;
    padding: 4px 2px;
  }

  & [data-epr-part='category-tab'] {
    width: 30px;
    height: 26px;
    padding: 2px 4px;
    border-radius: 0;
    background: var(--w95-face);
    box-shadow: inset -1px -1px var(--w95-darker), inset 1px 1px var(--w95-light), inset -2px -2px var(--w95-dark);
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-darker), inset 2px 2px var(--w95-dark);
  }

  & [data-epr-part='viewport'] {
    margin: 0 2px;
    background: #fff;
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark), inset 2px 2px var(--w95-darker);
  }

  & .w95-header {
    margin: 0;
    padding: 0 6px;
    background: #000080;
    color: #fff;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.04em;
  }

  & .w95-cell {
    border-radius: 0;
  }

  & .w95-cell:hover,
  & .w95-cell:focus {
    background: #000080;
  }

  & .w95-status {
    display: flex;
    gap: 6px;
    align-items: center;
    height: 22px;
    margin-top: 3px;
    padding: 0 6px;
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark);
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #000000;
  --epr-category-label-height: 22px;
  --epr-category-icon-active-color: #000000;
  --epr-category-icon-inactive-color: #404040;
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-variation-picker-bg-color: var(--w95-face);
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 6px;
  height: 360px;
  margin-top: 3px;
  background: var(--w95-face);

  & [data-epr-part='category-nav'] > * {
    justify-content: flex-start;
    gap: 2px;
    padding: 4px 2px;
  }

  & [data-epr-part='category-tab'] {
    width: 30px;
    height: 26px;
    padding: 2px 4px;
    border-radius: 0;
    background: var(--w95-face);
    box-shadow: inset -1px -1px var(--w95-darker), inset 1px 1px var(--w95-light), inset -2px -2px var(--w95-dark);
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-darker), inset 2px 2px var(--w95-dark);
  }

  & [data-epr-part='viewport'] {
    margin: 0 2px;
    background: #fff;
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark), inset 2px 2px var(--w95-darker);
  }

  & .w95-header {
    margin: 0;
    padding: 0 6px;
    background: #000080;
    color: #fff;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.04em;
  }

  & .w95-cell {
    border-radius: 0;
  }

  & .w95-cell:hover,
  & .w95-cell:focus {
    background: #000080;
  }

  & .w95-status {
    display: flex;
    gap: 6px;
    align-items: center;
    height: 22px;
    margin-top: 3px;
    padding: 0 6px;
    box-shadow: inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark);
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#000000",
  "--epr-category-label-height": "22px",
  "--epr-category-icon-active-color": "#000000",
  "--epr-category-icon-inactive-color": "#404040",
  "--epr-category-navigation-button-size": "22px",
  "--epr-emoji-variation-picker-bg-color": "var(--w95-face)",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "6px",
  height: "360px",
  marginTop: "3px",
  background: "var(--w95-face)",
  "& [data-epr-part='category-nav'] > *": {
    justifyContent: "flex-start",
    gap: "2px",
    padding: "4px 2px",
  },
  "& [data-epr-part='category-tab']": {
    width: "30px",
    height: "26px",
    padding: "2px 4px",
    borderRadius: "0",
    background: "var(--w95-face)",
    boxShadow: "inset -1px -1px var(--w95-darker), inset 1px 1px var(--w95-light), inset -2px -2px var(--w95-dark)",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    boxShadow: "inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-darker), inset 2px 2px var(--w95-dark)",
  },
  "& [data-epr-part='viewport']": {
    margin: "0 2px",
    background: "#fff",
    boxShadow: "inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark), inset 2px 2px var(--w95-darker)",
  },
  "& .w95-header": {
    margin: "0",
    padding: "0 6px",
    background: "#000080",
    color: "#fff",
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "0.04em",
  },
  "& .w95-cell": {
    borderRadius: "0",
  },
  "& .w95-cell:hover, & .w95-cell:focus": {
    background: "#000080",
  },
  "& .w95-status": {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    height: "22px",
    marginTop: "3px",
    padding: "0 6px",
    boxShadow: "inset -1px -1px var(--w95-light), inset 1px 1px var(--w95-dark)",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#000000]',
  '[--epr-category-label-height:22px]',
  '[--epr-category-icon-active-color:#000000]',
  '[--epr-category-icon-inactive-color:#404040]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-variation-picker-bg-color:var(--w95-face)]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:6px]',
  '[height:360px]',
  '[margin-top:3px]',
  '[background:var(--w95-face)]',
  '[&_[data-epr-part=category-nav]_>_*]:[justify-content:flex-start]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:2px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:4px_2px]',
  '[&_[data-epr-part=category-tab]]:[width:30px]',
  '[&_[data-epr-part=category-tab]]:[height:26px]',
  '[&_[data-epr-part=category-tab]]:[padding:2px_4px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:0]',
  '[&_[data-epr-part=category-tab]]:[background:var(--w95-face)]',
  '[&_[data-epr-part=category-tab]]:[box-shadow:inset_-1px_-1px_var(--w95-darker),_inset_1px_1px_var(--w95-light),_inset_-2px_-2px_var(--w95-dark)]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-darker),_inset_2px_2px_var(--w95-dark)]',
  '[&_[data-epr-part=viewport]]:[margin:0_2px]',
  '[&_[data-epr-part=viewport]]:[background:#fff]',
  '[&_[data-epr-part=viewport]]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-dark),_inset_2px_2px_var(--w95-darker)]',
  '[&_.w95-header]:[margin:0]',
  '[&_.w95-header]:[padding:0_6px]',
  '[&_.w95-header]:[background:#000080]',
  '[&_.w95-header]:[color:#fff]',
  '[&_.w95-header]:[font-size:11px]',
  '[&_.w95-header]:[font-weight:700]',
  '[&_.w95-header]:[letter-spacing:0.04em]',
  '[&_.w95-cell]:[border-radius:0]',
  '[&_.w95-cell:hover]:[background:#000080]',
  '[&_.w95-cell:focus]:[background:#000080]',
  '[&_.w95-status]:[display:flex]',
  '[&_.w95-status]:[gap:6px]',
  '[&_.w95-status]:[align-items:center]',
  '[&_.w95-status]:[height:22px]',
  '[&_.w95-status]:[margin-top:3px]',
  '[&_.w95-status]:[padding:0_6px]',
  '[&_.w95-status]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-dark)]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#000000"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-category-label-height:22px]',
  '[--epr-category-icon-active-color:#000000]',
  '[--epr-category-icon-inactive-color:#404040]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-variation-picker-bg-color:var(--w95-face)]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:6px]',
  '[height:360px]',
  '[margin-top:3px]',
  '[background:var(--w95-face)]',
  '[&_[data-epr-part=category-nav]_>_*]:[justify-content:flex-start]',
  '[&_[data-epr-part=category-nav]_>_*]:[gap:2px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:4px_2px]',
  '[&_[data-epr-part=category-tab]]:[width:30px]',
  '[&_[data-epr-part=category-tab]]:[height:26px]',
  '[&_[data-epr-part=category-tab]]:[padding:2px_4px]',
  '[&_[data-epr-part=category-tab]]:[border-radius:0]',
  '[&_[data-epr-part=category-tab]]:[background:var(--w95-face)]',
  '[&_[data-epr-part=category-tab]]:[box-shadow:inset_-1px_-1px_var(--w95-darker),_inset_1px_1px_var(--w95-light),_inset_-2px_-2px_var(--w95-dark)]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-darker),_inset_2px_2px_var(--w95-dark)]',
  '[&_[data-epr-part=viewport]]:[margin:0_2px]',
  '[&_[data-epr-part=viewport]]:[background:#fff]',
  '[&_[data-epr-part=viewport]]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-dark),_inset_2px_2px_var(--w95-darker)]',
  '[&_.w95-header]:[margin:0]',
  '[&_.w95-header]:[padding:0_6px]',
  '[&_.w95-header]:[background:#000080]',
  '[&_.w95-header]:[color:#fff]',
  '[&_.w95-header]:[font-size:11px]',
  '[&_.w95-header]:[font-weight:700]',
  '[&_.w95-header]:[letter-spacing:0.04em]',
  '[&_.w95-cell]:[border-radius:0]',
  '[&_.w95-cell:hover]:[background:#000080]',
  '[&_.w95-cell:focus]:[background:#000080]',
  '[&_.w95-status]:[display:flex]',
  '[&_.w95-status]:[gap:6px]',
  '[&_.w95-status]:[align-items:center]',
  '[&_.w95-status]:[height:22px]',
  '[&_.w95-status]:[margin-top:3px]',
  '[&_.w95-status]:[padding:0_6px]',
  '[&_.w95-status]:[box-shadow:inset_-1px_-1px_var(--w95-light),_inset_1px_1px_var(--w95-dark)]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
