// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Polaris rating card',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="polaris-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #f7f7f7;
  --epr-hover-bg-color: #ebebeb;
  --epr-focus-bg-color: #e3e3e3;
  --epr-category-label-height: 0px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 8px;
  height: 128px;
  border: 1px solid #e3e3e3;
  border-radius: 8px;
  background: var(--epr-bg-color);

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='list'] {
    padding: 6px 0;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #f7f7f7;
  --epr-hover-bg-color: #ebebeb;
  --epr-focus-bg-color: #e3e3e3;
  --epr-category-label-height: 0px;
  --epr-emoji-size: 26px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 8px;
  height: 128px;
  border: 1px solid #e3e3e3;
  border-radius: 8px;
  background: var(--epr-bg-color);

  & [data-epr-part='category-label'] {
    display: none;
  }

  & [data-epr-part='list'] {
    padding: 6px 0;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#f7f7f7",
  "--epr-hover-bg-color": "#ebebeb",
  "--epr-focus-bg-color": "#e3e3e3",
  "--epr-category-label-height": "0px",
  "--epr-emoji-size": "26px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "8px",
  height: "128px",
  border: "1px solid #e3e3e3",
  borderRadius: "8px",
  background: "var(--epr-bg-color)",
  "& [data-epr-part='category-label']": {
    display: "none",
  },
  "& [data-epr-part='list']": {
    padding: "6px 0",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "8px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#f7f7f7]',
  '[--epr-hover-bg-color:#ebebeb]',
  '[--epr-focus-bg-color:#e3e3e3]',
  '[--epr-category-label-height:0px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:8px]',
  '[height:128px]',
  '[border:1px_solid_#e3e3e3]',
  '[border-radius:8px]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=list]]:[padding:6px_0]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#f7f7f7",
  "--accent": "#ebebeb"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e3e3e3]',
  '[--epr-category-label-height:0px]',
  '[--epr-emoji-size:26px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:8px]',
  '[height:128px]',
  '[border:1px_solid_#e3e3e3]',
  '[border-radius:8px]',
  '[background:var(--epr-bg-color)]',
  '[&_[data-epr-part=category-label]]:[display:none]',
  '[&_[data-epr-part=list]]:[padding:6px_0]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
