// Generates src/components/icons/svgIcons.ts from the SVG sources.
//
// Icons ship as base64 data URIs in plain TS: importing .svg files relies
// on bundler loaders whose output differs (esbuild emits raw-text data
// URLs that are invalid inside CSS url(), Vite URL-encodes them with
// unbalanced parentheses), which left the icons blank in published
// bundles. Run after editing an icon: node ./scripts/buildIcons.js
const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

const src = join(__dirname, '..', 'src', 'components');
const icons = {
  PLUS_ICON: 'Reactions/svg/plus.svg',
  TRIANGLE_ICON: 'body/svg/triangle.svg',
  MAGNIFIER_ICON: 'header/Search/svg/magnifier.svg',
  TIMES_ICON: 'header/Search/svg/times.svg',
};

const minify = (svg) =>
  svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/>\s+</g, '><')
    .replace(/\s+/g, ' ')
    .trim();

const lines = Object.entries(icons).map(([name, file]) => {
  const svg = minify(readFileSync(join(src, file), 'utf8'));
  const uri = `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
  return `// ${file}\nexport const ${name} =\n  '${uri}';`;
});

writeFileSync(
  join(src, 'icons', 'svgIcons.ts'),
  `// Generated by scripts/buildIcons.js — do not edit.\n\n${lines.join('\n\n')}\n`,
);
