/* eslint-disable @typescript-eslint/no-var-requires */
// Concatenates the distributable docs into a single llms.txt for LLM consumers.
// Run: npm run docs:llms
const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

const root = join(__dirname, '..');

const sources = [
  'README.md',
  'PROPS.md',
  'CUSTOMIZATION.md',
  'INTERNATIONALIZATION.md',
  'CSS_VARIABLES.md',
];

const parts = [
  '# emoji-picker-react — LLM context',
  '',
  '> This file is auto-generated by `npm run docs:llms`. Do not edit by hand.',
  `> Sources: ${sources.join(', ')}`,
];

for (const file of sources) {
  const content = readFileSync(join(root, file), 'utf8').trim();
  parts.push('', `<!-- source: ${file} -->`, '', content);
}

writeFileSync(join(root, 'llms.txt'), `${parts.join('\n')}\n`);
console.log(`llms.txt written from ${sources.length} sources.`);
