// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Discord sidebar',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="discord-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #2b2d31;
  --epr-text-color: #dbdee1;
  --epr-highlight-color: #5865f2;
  --epr-hover-bg-color: #3f4248;
  --epr-focus-bg-color: #404249;
  --epr-picker-border-color: #1e1f22;
  --epr-search-input-bg-color: #1e1f22;
  --epr-search-input-text-color: #dbdee1;
  --epr-search-input-placeholder-color: #949ba4;
  --epr-search-border-color: #1e1f22;
  --epr-search-border-color-active: #5865f2;
  --epr-search-input-border-radius: 4px;
  --epr-search-input-height: 30px;
  --epr-category-label-bg-color: #2b2d31f2;
  --epr-category-label-text-color: #b5bac1;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #dbdee1;
  --epr-category-icon-inactive-color: #80848e;
  --epr-category-navigation-button-size: 24px;
  --epr-preview-border-color: #1e1f22;
  --epr-preview-text-color: #f2f3f5;
  --epr-preview-height: 52px;
  --epr-preview-emoji-size: 30px;
  --epr-skin-tone-picker-menu-color: #2b2d31f5;
  --epr-emoji-variation-picker-bg-color: #232428;
  --epr-emoji-size: 32px;
  --epr-emoji-padding: 4px;
  width: 420px;
  height: 440px;
  border-radius: 8px;
  background: var(--epr-bg-color);
  box-shadow: 0 8px 16px rgb(0 0 0 / 24%);
  font-family: 'gg sans', 'Noto Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: var(--epr-text-color);

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='preview'] {
    background: #232428;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #2b2d31;
  --epr-text-color: #dbdee1;
  --epr-highlight-color: #5865f2;
  --epr-hover-bg-color: #3f4248;
  --epr-focus-bg-color: #404249;
  --epr-picker-border-color: #1e1f22;
  --epr-search-input-bg-color: #1e1f22;
  --epr-search-input-text-color: #dbdee1;
  --epr-search-input-placeholder-color: #949ba4;
  --epr-search-border-color: #1e1f22;
  --epr-search-border-color-active: #5865f2;
  --epr-search-input-border-radius: 4px;
  --epr-search-input-height: 30px;
  --epr-category-label-bg-color: #2b2d31f2;
  --epr-category-label-text-color: #b5bac1;
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #dbdee1;
  --epr-category-icon-inactive-color: #80848e;
  --epr-category-navigation-button-size: 24px;
  --epr-preview-border-color: #1e1f22;
  --epr-preview-text-color: #f2f3f5;
  --epr-preview-height: 52px;
  --epr-preview-emoji-size: 30px;
  --epr-skin-tone-picker-menu-color: #2b2d31f5;
  --epr-emoji-variation-picker-bg-color: #232428;
  --epr-emoji-size: 32px;
  --epr-emoji-padding: 4px;
  width: 420px;
  height: 440px;
  border-radius: 8px;
  background: var(--epr-bg-color);
  box-shadow: 0 8px 16px rgb(0 0 0 / 24%);
  font-family: 'gg sans', 'Noto Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: var(--epr-text-color);

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='preview'] {
    background: #232428;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#2b2d31",
  "--epr-text-color": "#dbdee1",
  "--epr-highlight-color": "#5865f2",
  "--epr-hover-bg-color": "#3f4248",
  "--epr-focus-bg-color": "#404249",
  "--epr-picker-border-color": "#1e1f22",
  "--epr-search-input-bg-color": "#1e1f22",
  "--epr-search-input-text-color": "#dbdee1",
  "--epr-search-input-placeholder-color": "#949ba4",
  "--epr-search-border-color": "#1e1f22",
  "--epr-search-border-color-active": "#5865f2",
  "--epr-search-input-border-radius": "4px",
  "--epr-search-input-height": "30px",
  "--epr-category-label-bg-color": "#2b2d31f2",
  "--epr-category-label-text-color": "#b5bac1",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "#dbdee1",
  "--epr-category-icon-inactive-color": "#80848e",
  "--epr-category-navigation-button-size": "24px",
  "--epr-preview-border-color": "#1e1f22",
  "--epr-preview-text-color": "#f2f3f5",
  "--epr-preview-height": "52px",
  "--epr-preview-emoji-size": "30px",
  "--epr-skin-tone-picker-menu-color": "#2b2d31f5",
  "--epr-emoji-variation-picker-bg-color": "#232428",
  "--epr-emoji-size": "32px",
  "--epr-emoji-padding": "4px",
  width: "420px",
  height: "440px",
  borderRadius: "8px",
  background: "var(--epr-bg-color)",
  boxShadow: "0 8px 16px rgb(0 0 0 / 24%)",
  fontFamily: "'gg sans', 'Noto Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif",
  color: "var(--epr-text-color)",
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "4px",
  },
  "& [data-epr-part='preview']": {
    background: "#232428",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#2b2d31]',
  '[--epr-text-color:#dbdee1]',
  '[--epr-highlight-color:#5865f2]',
  '[--epr-hover-bg-color:#3f4248]',
  '[--epr-focus-bg-color:#404249]',
  '[--epr-picker-border-color:#1e1f22]',
  '[--epr-search-input-bg-color:#1e1f22]',
  '[--epr-search-input-text-color:#dbdee1]',
  '[--epr-search-input-placeholder-color:#949ba4]',
  '[--epr-search-border-color:#1e1f22]',
  '[--epr-search-border-color-active:#5865f2]',
  '[--epr-search-input-border-radius:4px]',
  '[--epr-search-input-height:30px]',
  '[--epr-category-label-bg-color:#2b2d31f2]',
  '[--epr-category-label-text-color:#b5bac1]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#dbdee1]',
  '[--epr-category-icon-inactive-color:#80848e]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-preview-border-color:#1e1f22]',
  '[--epr-preview-text-color:#f2f3f5]',
  '[--epr-preview-height:52px]',
  '[--epr-preview-emoji-size:30px]',
  '[--epr-skin-tone-picker-menu-color:#2b2d31f5]',
  '[--epr-emoji-variation-picker-bg-color:#232428]',
  '[--epr-emoji-size:32px]',
  '[--epr-emoji-padding:4px]',
  '[width:420px]',
  '[height:440px]',
  '[border-radius:8px]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_8px_16px_rgb(0_0_0_/_24%)]',
  "[font-family:'gg_sans',_'Noto_Sans',_'Helvetica_Neue',_Helvetica,_Arial,_sans-serif]",
  '[color:var(--epr-text-color)]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.02em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=preview]]:[background:#232428]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#2b2d31",
  "--muted-foreground": "#dbdee1",
  "--primary": "#5865f2",
  "--accent": "#3f4248",
  "--border": "#1e1f22",
  "--popover-foreground": "#dbdee1",
  "--input": "#1e1f22",
  "--ring": "#5865f2"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#404249]',
  '[--epr-picker-border-color:var(--border)]',
  '[--epr-search-input-bg-color:#1e1f22]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#949ba4]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-border-radius:4px]',
  '[--epr-search-input-height:30px]',
  '[--epr-category-label-bg-color:#2b2d31f2]',
  '[--epr-category-label-text-color:#b5bac1]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#dbdee1]',
  '[--epr-category-icon-inactive-color:#80848e]',
  '[--epr-category-navigation-button-size:24px]',
  '[--epr-preview-border-color:#1e1f22]',
  '[--epr-preview-text-color:#f2f3f5]',
  '[--epr-preview-height:52px]',
  '[--epr-preview-emoji-size:30px]',
  '[--epr-skin-tone-picker-menu-color:#2b2d31f5]',
  '[--epr-emoji-variation-picker-bg-color:#232428]',
  '[--epr-emoji-size:32px]',
  '[--epr-emoji-padding:4px]',
  '[width:420px]',
  '[height:440px]',
  '[border-radius:8px]',
  '[background:var(--epr-bg-color)]',
  '[box-shadow:0_8px_16px_rgb(0_0_0_/_24%)]',
  "[font-family:'gg_sans',_'Noto_Sans',_'Helvetica_Neue',_Helvetica,_Arial,_sans-serif]",
  '[color:var(--epr-text-color)]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[letter-spacing:0.02em]',
  '[&_[data-epr-part=category-label]]:[text-transform:uppercase]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=preview]]:[background:#232428]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
