// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/Community custom emojis',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="forum-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #52525b;
  --epr-highlight-color: #16a34a;
  --epr-hover-bg-color: #f0fdf4;
  --epr-focus-bg-color: #dcfce7;
  --epr-search-input-bg-color: #fafafa;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #e4e4e7;
  --epr-search-border-color-active: #16a34a;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #18181b;
  --epr-search-input-placeholder-color: #71717a;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #52525b;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #15803d;
  --epr-category-icon-inactive-color: #71717a;
  --epr-category-navigation-button-size: 20px;
  --epr-skin-tone-picker-menu-color: #ffffff;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 8px;
  height: 300px;
  border: 1px solid #e4e4e7;
  border-radius: 10px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 10px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #dcfce7;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #52525b;
  --epr-highlight-color: #16a34a;
  --epr-hover-bg-color: #f0fdf4;
  --epr-focus-bg-color: #dcfce7;
  --epr-search-input-bg-color: #fafafa;
  --epr-search-input-bg-color-active: #ffffff;
  --epr-search-border-color: #e4e4e7;
  --epr-search-border-color-active: #16a34a;
  --epr-search-input-height: 34px;
  --epr-search-input-border-radius: 8px;
  --epr-search-input-text-color: #18181b;
  --epr-search-input-placeholder-color: #71717a;
  --epr-category-label-bg-color: #fffffff2;
  --epr-category-label-text-color: #52525b;
  --epr-category-label-height: 28px;
  --epr-category-icon-active-color: #15803d;
  --epr-category-icon-inactive-color: #71717a;
  --epr-category-navigation-button-size: 20px;
  --epr-skin-tone-picker-menu-color: #ffffff;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 8px;
  height: 300px;
  border: 1px solid #e4e4e7;
  border-radius: 10px;
  background: #ffffff;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;

  & [data-epr-part='search'] > * {
    padding: 10px 10px 4px;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 10px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    border-radius: 6px;
    background-color: #dcfce7;
  }

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 600;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 8px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#52525b",
  "--epr-highlight-color": "#16a34a",
  "--epr-hover-bg-color": "#f0fdf4",
  "--epr-focus-bg-color": "#dcfce7",
  "--epr-search-input-bg-color": "#fafafa",
  "--epr-search-input-bg-color-active": "#ffffff",
  "--epr-search-border-color": "#e4e4e7",
  "--epr-search-border-color-active": "#16a34a",
  "--epr-search-input-height": "34px",
  "--epr-search-input-border-radius": "8px",
  "--epr-search-input-text-color": "#18181b",
  "--epr-search-input-placeholder-color": "#71717a",
  "--epr-category-label-bg-color": "#fffffff2",
  "--epr-category-label-text-color": "#52525b",
  "--epr-category-label-height": "28px",
  "--epr-category-icon-active-color": "#15803d",
  "--epr-category-icon-inactive-color": "#71717a",
  "--epr-category-navigation-button-size": "20px",
  "--epr-skin-tone-picker-menu-color": "#ffffff",
  "--epr-emoji-size": "28px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "8px",
  height: "300px",
  border: "1px solid #e4e4e7",
  borderRadius: "10px",
  background: "#ffffff",
  fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "& [data-epr-part='search'] > *": {
    padding: "10px 10px 4px",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "6px 10px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    borderRadius: "6px",
    backgroundColor: "#dcfce7",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "8px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#52525b]',
  '[--epr-highlight-color:#16a34a]',
  '[--epr-hover-bg-color:#f0fdf4]',
  '[--epr-focus-bg-color:#dcfce7]',
  '[--epr-search-input-bg-color:#fafafa]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:#e4e4e7]',
  '[--epr-search-border-color-active:#16a34a]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:#18181b]',
  '[--epr-search-input-placeholder-color:#71717a]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#52525b]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#15803d]',
  '[--epr-category-icon-inactive-color:#71717a]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-skin-tone-picker-menu-color:#ffffff]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:8px]',
  '[height:300px]',
  '[border:1px_solid_#e4e4e7]',
  '[border-radius:10px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#dcfce7]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#52525b",
  "--primary": "#16a34a",
  "--accent": "#f0fdf4",
  "--input": "#e4e4e7",
  "--ring": "#16a34a",
  "--popover-foreground": "#18181b"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#dcfce7]',
  '[--epr-search-input-bg-color:#fafafa]',
  '[--epr-search-input-bg-color-active:#ffffff]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:34px]',
  '[--epr-search-input-border-radius:8px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#71717a]',
  '[--epr-category-label-bg-color:#fffffff2]',
  '[--epr-category-label-text-color:#52525b]',
  '[--epr-category-label-height:28px]',
  '[--epr-category-icon-active-color:#15803d]',
  '[--epr-category-icon-inactive-color:#71717a]',
  '[--epr-category-navigation-button-size:20px]',
  '[--epr-skin-tone-picker-menu-color:#ffffff]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:8px]',
  '[height:300px]',
  '[border:1px_solid_#e4e4e7]',
  '[border-radius:10px]',
  '[background:#ffffff]',
  "[font-family:ui-sans-serif,_system-ui,_-apple-system,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_sans-serif]",
  '[&_[data-epr-part=search]_>_*]:[padding:10px_10px_4px]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[border-radius:6px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[background-color:#dcfce7]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:600]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:8px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
