// Generated by scripts/generateRecipes.mjs from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Notion icon picker',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="notion-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #37352f;
  --epr-highlight-color: #2383e2;
  --epr-hover-bg-color: #efefef;
  --epr-focus-bg-color: #e8e8e6;
  --epr-search-input-bg-color: #f1f1ef;
  --epr-search-input-bg-color-active: #f1f1ef;
  --epr-search-border-color: rgb(55 53 47 / 16%);
  --epr-search-border-color-active: #2383e2;
  --epr-search-input-height: 28px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-padding: 0 8px 0 34px;
  --epr-search-input-placeholder-color: rgb(55 53 47 / 50%);
  --epr-category-label-bg-color: #ffffff;
  --epr-category-label-text-color: rgb(55 53 47 / 82%);
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #37352f;
  --epr-category-icon-inactive-color: rgb(55 53 47 / 45%);
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  width: 408px;
  height: 386px;
  border-radius: 10px;
  background: #fff;
  box-shadow: rgb(15 15 15 / 5%) 0 0 0 1px, rgb(15 15 15 / 10%) 0 3px 6px, rgb(15 15 15 / 20%) 0 9px 24px;
  font-family: ui-sans-serif, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
  color: #37352f;

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 500;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='category-nav'] {
    border-top: 1px solid rgb(55 53 47 / 9%);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 10px;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #ffffff;
  --epr-text-color: #37352f;
  --epr-highlight-color: #2383e2;
  --epr-hover-bg-color: #efefef;
  --epr-focus-bg-color: #e8e8e6;
  --epr-search-input-bg-color: #f1f1ef;
  --epr-search-input-bg-color-active: #f1f1ef;
  --epr-search-border-color: rgb(55 53 47 / 16%);
  --epr-search-border-color-active: #2383e2;
  --epr-search-input-height: 28px;
  --epr-search-input-border-radius: 6px;
  --epr-search-input-padding: 0 8px 0 34px;
  --epr-search-input-placeholder-color: rgb(55 53 47 / 50%);
  --epr-category-label-bg-color: #ffffff;
  --epr-category-label-text-color: rgb(55 53 47 / 82%);
  --epr-category-label-height: 30px;
  --epr-category-icon-active-color: #37352f;
  --epr-category-icon-inactive-color: rgb(55 53 47 / 45%);
  --epr-category-navigation-button-size: 22px;
  --epr-emoji-size: 24px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 12px;
  width: 408px;
  height: 386px;
  border-radius: 10px;
  background: #fff;
  box-shadow: rgb(15 15 15 / 5%) 0 0 0 1px, rgb(15 15 15 / 10%) 0 3px 6px, rgb(15 15 15 / 20%) 0 9px 24px;
  font-family: ui-sans-serif, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
  color: #37352f;

  & [data-epr-part='category-label'] {
    font-size: 12px;
    font-weight: 500;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 4px;
  }

  & [data-epr-part='category-nav'] {
    border-top: 1px solid rgb(55 53 47 / 9%);
  }

  & [data-epr-part='category-nav'] > * {
    padding: 6px 10px;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#ffffff",
  "--epr-text-color": "#37352f",
  "--epr-highlight-color": "#2383e2",
  "--epr-hover-bg-color": "#efefef",
  "--epr-focus-bg-color": "#e8e8e6",
  "--epr-search-input-bg-color": "#f1f1ef",
  "--epr-search-input-bg-color-active": "#f1f1ef",
  "--epr-search-border-color": "rgb(55 53 47 / 16%)",
  "--epr-search-border-color-active": "#2383e2",
  "--epr-search-input-height": "28px",
  "--epr-search-input-border-radius": "6px",
  "--epr-search-input-padding": "0 8px 0 34px",
  "--epr-search-input-placeholder-color": "rgb(55 53 47 / 50%)",
  "--epr-category-label-bg-color": "#ffffff",
  "--epr-category-label-text-color": "rgb(55 53 47 / 82%)",
  "--epr-category-label-height": "30px",
  "--epr-category-icon-active-color": "#37352f",
  "--epr-category-icon-inactive-color": "rgb(55 53 47 / 45%)",
  "--epr-category-navigation-button-size": "22px",
  "--epr-emoji-size": "24px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "12px",
  width: "408px",
  height: "386px",
  borderRadius: "10px",
  background: "#fff",
  boxShadow: "rgb(15 15 15 / 5%) 0 0 0 1px, rgb(15 15 15 / 10%) 0 3px 6px, rgb(15 15 15 / 20%) 0 9px 24px",
  fontFamily: "ui-sans-serif, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
  color: "#37352f",
  "& [data-epr-part='category-label']": {
    fontSize: "12px",
    fontWeight: "500",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "4px",
  },
  "& [data-epr-part='category-nav']": {
    borderTop: "1px solid rgb(55 53 47 / 9%)",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "6px 10px",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. Requires `@layer epr;` before Tailwind (see tailwind.css).
 */
const tailwind = [
  '[--epr-bg-color:#ffffff]',
  '[--epr-text-color:#37352f]',
  '[--epr-highlight-color:#2383e2]',
  '[--epr-hover-bg-color:#efefef]',
  '[--epr-focus-bg-color:#e8e8e6]',
  '[--epr-search-input-bg-color:#f1f1ef]',
  '[--epr-search-input-bg-color-active:#f1f1ef]',
  '[--epr-search-border-color:rgb(55_53_47_/_16%)]',
  '[--epr-search-border-color-active:#2383e2]',
  '[--epr-search-input-height:28px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-padding:0_8px_0_34px]',
  '[--epr-search-input-placeholder-color:rgb(55_53_47_/_50%)]',
  '[--epr-category-label-bg-color:#ffffff]',
  '[--epr-category-label-text-color:rgb(55_53_47_/_82%)]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#37352f]',
  '[--epr-category-icon-inactive-color:rgb(55_53_47_/_45%)]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[width:408px]',
  '[height:386px]',
  '[border-radius:10px]',
  '[background:#fff]',
  '[box-shadow:rgb(15_15_15_/_5%)_0_0_0_1px,_rgb(15_15_15_/_10%)_0_3px_6px,_rgb(15_15_15_/_20%)_0_9px_24px]',
  "[font-family:ui-sans-serif,_-apple-system,_'Segoe_UI',_Helvetica,_Arial,_sans-serif]",
  '[color:#37352f]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=category-nav]]:[border-top:1px_solid_rgb(55_53_47_/_9%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
].join(' ');

export const Tailwind = () => <Shell className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#ffffff",
  "--muted-foreground": "#37352f",
  "--primary": "#2383e2",
  "--accent": "#efefef",
  "--input": "rgb(55 53 47 / 16%)",
  "--ring": "#2383e2"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:#e8e8e6]',
  '[--epr-search-input-bg-color:#f1f1ef]',
  '[--epr-search-input-bg-color-active:#f1f1ef]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:28px]',
  '[--epr-search-input-border-radius:6px]',
  '[--epr-search-input-padding:0_8px_0_34px]',
  '[--epr-search-input-placeholder-color:rgb(55_53_47_/_50%)]',
  '[--epr-category-label-bg-color:#ffffff]',
  '[--epr-category-label-text-color:rgb(55_53_47_/_82%)]',
  '[--epr-category-label-height:30px]',
  '[--epr-category-icon-active-color:#37352f]',
  '[--epr-category-icon-inactive-color:rgb(55_53_47_/_45%)]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-emoji-size:24px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:12px]',
  '[width:408px]',
  '[height:386px]',
  '[border-radius:10px]',
  '[background:#fff]',
  '[box-shadow:rgb(15_15_15_/_5%)_0_0_0_1px,_rgb(15_15_15_/_10%)_0_3px_6px,_rgb(15_15_15_/_20%)_0_9px_24px]',
  "[font-family:ui-sans-serif,_-apple-system,_'Segoe_UI',_Helvetica,_Arial,_sans-serif]",
  '[color:#37352f]',
  '[&_[data-epr-part=category-label]]:[font-size:12px]',
  '[&_[data-epr-part=category-label]]:[font-weight:500]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:4px]',
  '[&_[data-epr-part=category-nav]]:[border-top:1px_solid_rgb(55_53_47_/_9%)]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:6px_10px]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell className={shadcn} />
  </div>
);
