const COLOR_GREY_50 = '#fafafa';
const COLOR_GREY_100 = '#f5f5f5';
const COLOR_GREY_200 = '#eeeeee';
const COLOR_GREY_300 = '#e0e0e0';
const COLOR_GREY_400 = '#bdbdbd';
const COLOR_GREY_500 = '#9e9e9e';
const COLOR_BLUE_200 = '#90caf9';
const COLOR_GREEN_200 = '#a5d6a7';
const COLOR_WHITE = '#ffffff';

const BORDER_MAIN = COLOR_GREY_200;
const BG_NAV = COLOR_WHITE;
const PADDING_EMOJI_LIST = '5px';
const PADDING_CATEGORY_NAME = '10px';
const COLOR_NAV_UNDERLINE_HOVER = COLOR_GREEN_200;
const HEIGHT_NAV_ITEM = '45px';
const WIDTH_NAV_ITEM = '20px';
const COLOR_NAV_UNDERLINE_ACTIVE = COLOR_BLUE_200;

const BG_DIVERSITY_PICKER = COLOR_GREY_50;
const HEIGHT_DIVERSITY_PICKER = '30px';
const BORDER_DIVERSITY_PICKER = BORDER_MAIN;
const SIZE_EMOJI = '20px';

export {
    COLOR_GREY_50,
    COLOR_GREY_100,
    COLOR_GREY_200,
    COLOR_GREY_300,
    COLOR_GREY_400,
    COLOR_GREY_500,
    COLOR_BLUE_200,
    COLOR_GREEN_200,
    COLOR_WHITE,
    BORDER_MAIN,
    BG_NAV,
    PADDING_EMOJI_LIST,
    PADDING_CATEGORY_NAME,
    COLOR_NAV_UNDERLINE_HOVER,
    HEIGHT_NAV_ITEM,
    WIDTH_NAV_ITEM,
    COLOR_NAV_UNDERLINE_ACTIVE,
    BG_DIVERSITY_PICKER,
    HEIGHT_DIVERSITY_PICKER,
    BORDER_DIVERSITY_PICKER,
    SIZE_EMOJI
};