// Generated by scripts/portDesigns.mjs from stories/recipes/*/recipe.json.
import { Shell as TeamChat } from './TeamChat';
import { Shell as ArticleComments } from './ArticleComments';
import { Shell as EditorInsertPanel } from './EditorInsertPanel';
import { Shell as LivestreamChat } from './LivestreamChat';
import { Shell as StatusDialog } from './StatusDialog';
import { Shell as ShortcodeTypeahead } from './ShortcodeTypeahead';
import { Shell as VideoCallReactions } from './VideoCallReactions';
import { Shell as CommunityForum } from './CommunityForum';
import { Shell as ProjectIconPicker } from './ProjectIconPicker';
import { Shell as HabitTrackerMobile } from './HabitTrackerMobile';
import { Shell as DiscordSidebar } from './DiscordSidebar';
import { Shell as SlackReactions } from './SlackReactions';
import { Shell as GithubReactions } from './GithubReactions';
import { Shell as IMessageTapback } from './IMessageTapback';
import { Shell as XComposer } from './XComposer';
import { Shell as NotionIconPicker } from './NotionIconPicker';
import { Shell as LinearPalette } from './LinearPalette';
import { Shell as TeamsFluent } from './TeamsFluent';
import { Shell as Material3 } from './Material3';
import { Shell as GeistMinimal } from './GeistMinimal';
import { Shell as PolarisRating } from './PolarisRating';
import { Shell as IntercomRating } from './IntercomRating';
import { Shell as IosBottomSheet } from './IosBottomSheet';
import { Shell as WhatsAppKeyboard } from './WhatsAppKeyboard';
import { Shell as Windows95 } from './Windows95';

export const DESIGN_EXAMPLES = [
  {
    id: "team-chat",
    title: "Team chat composer",
    description: "A popover above a chat composer: search with skin tone, tabs, grid and a slim preview.",
    rootClass: "chat-picker",
    kind: "In context",
    Example: TeamChat,
  },
  {
    id: "article-comments",
    title: "Article comments",
    description: "Reaction count chips plus a compact reactions bar that expands to the full picker.",
    rootClass: "comments-picker",
    kind: "In context",
    Example: ArticleComments,
  },
  {
    id: "editor-insert-panel",
    title: "Doc editor insert panel",
    description: "A side-by-side panel: vertical rail, grid and a details pane via useActiveEmoji().",
    rootClass: "editor-picker",
    kind: "In context",
    Example: EditorInsertPanel,
  },
  {
    id: "livestream-chat",
    title: "Livestream chat",
    description: "Docked under a dark chat column: tabs on top and a dense grid.",
    rootClass: "stream-picker",
    kind: "In context",
    Example: LivestreamChat,
  },
  {
    id: "status-dialog",
    title: "Set a status dialog",
    description: "An inline form section with status-friendly suggestions and renamed categories.",
    rootClass: "status-picker",
    kind: "In context",
    Example: StatusDialog,
  },
  {
    id: "shortcode-typeahead",
    title: "Shortcode typeahead",
    description: "Editable :name autocomplete: type a query, press Down then Enter to replace the token, or Escape to dismiss.",
    rootClass: "typeahead-picker",
    kind: "In context",
    Example: ShortcodeTypeahead,
  },
  {
    id: "video-call-reactions",
    title: "Video call reactions",
    description: "A translucent reactions pill over video that expands to a dark picker.",
    rootClass: "call-picker",
    kind: "In context",
    Example: VideoCallReactions,
  },
  {
    id: "community-forum",
    title: "Community custom emojis",
    description: "Community custom emojis as their own group, before the standard set.",
    rootClass: "forum-picker",
    kind: "In context",
    Example: CommunityForum,
  },
  {
    id: "project-icon-picker",
    title: "Project icon picker",
    description: "A settings form: picking sets the project icon; categories are narrowed.",
    rootClass: "project-picker",
    kind: "In context",
    Example: ProjectIconPicker,
  },
  {
    id: "habit-tracker-mobile",
    title: "Habit tracker (mobile)",
    description: "A mobile bottom sheet with large, tile-style emojis.",
    rootClass: "habit-picker",
    kind: "In context",
    Example: HabitTrackerMobile,
  },
  {
    id: "discord-sidebar",
    title: "Discord sidebar",
    description: "A Discord-style picker with the category rail in its own vertical column.",
    rootClass: "discord-picker",
    kind: "In context",
    Example: DiscordSidebar,
  },
  {
    id: "slack-reactions",
    title: "Slack reactions",
    description: "The default picker in reactions mode with Slack's common reaction set.",
    rootClass: "slack-picker",
    kind: "In context",
    Example: SlackReactions,
  },
  {
    id: "github-reactions",
    title: "GitHub reactions",
    description: "GitHub's fixed reaction set as a compact bar that never expands.",
    rootClass: "gh-picker",
    kind: "In context",
    Example: GithubReactions,
  },
  {
    id: "imessage-tapback",
    title: "iMessage tapback",
    description: "An iMessage tapback bubble: love, like, dislike, laugh, emphasize, question.",
    rootClass: "imessage-picker",
    kind: "In context",
    Example: IMessageTapback,
  },
  {
    id: "x-composer",
    title: "X composer",
    description: "An X post composer with the skin tone control beside the search field.",
    rootClass: "x-picker",
    kind: "In context",
    Example: XComposer,
  },
  {
    id: "notion-icon-picker",
    title: "Notion icon picker",
    description: "A Notion page-icon popover with app tabs, Remove and Random inside the picker.",
    rootClass: "notion-picker",
    kind: "In context",
    Example: NotionIconPicker,
  },
  {
    id: "linear-palette",
    title: "Linear command palette",
    description: "A Linear command palette: search and grid only, no tabs and no preview.",
    rootClass: "linear-picker",
    kind: "In context",
    Example: LinearPalette,
  },
  {
    id: "teams-fluent",
    title: "Teams (Fluent 2)",
    description: "Microsoft Teams in Fluent 2: tabs first, then search.",
    rootClass: "teams-picker",
    kind: "In context",
    Example: TeamsFluent,
  },
  {
    id: "material-3",
    title: "Material 3",
    description: "Material 3 with a bottom navigation bar and the M3 pill indicator.",
    rootClass: "m3-picker",
    kind: "In context",
    Example: Material3,
  },
  {
    id: "geist-minimal",
    title: "Geist minimal",
    description: "A minimal Geist look: default light tokens with a few CSS adjustments.",
    rootClass: "geist-picker",
    kind: "In context",
    Example: GeistMinimal,
  },
  {
    id: "polaris-rating",
    title: "Polaris rating card",
    description: "A Polaris rating card narrowed to a single category.",
    rootClass: "polaris-picker",
    kind: "In context",
    Example: PolarisRating,
  },
  {
    id: "intercom-rating",
    title: "Intercom rating",
    description: "An Intercom-style satisfaction scale built from a stretched reactions bar.",
    rootClass: "intercom-scale",
    kind: "In context",
    Example: IntercomRating,
  },
  {
    id: "ios-bottom-sheet",
    title: "iOS bottom sheet",
    description: "A narrow, touch-first iOS bottom sheet without search.",
    rootClass: "ios-sheet",
    kind: "In context",
    Example: IosBottomSheet,
  },
  {
    id: "whatsapp-keyboard",
    title: "WhatsApp keyboard panel",
    description: "A full-width, short WhatsApp keyboard panel whose grid reflows its columns.",
    rootClass: "wa-picker",
    kind: "In context",
    Example: WhatsAppKeyboard,
  },
  {
    id: "windows-95",
    title: "Windows 95",
    description: "Windows 95, with custom markup for every emoji cell and section header.",
    rootClass: "w95-picker",
    kind: "In context",
    Example: Windows95,
  },
];
