// Generated by scripts/generateRecipes.mts from picker.css — do not edit.
// Change picker.css or shell.tsx, then run `npm run recipes`.
//
// The same design in seven styling stacks. Every variant renders the shared
// shell (shell.tsx) and is screenshot-tested against one baseline.
import styledEmotion from '@emotion/styled';
import { styled as styledMui } from '@mui/material/styles';
import type { Meta } from '@storybook/react-vite';
import React from 'react';
import styledComponents from 'styled-components';

import * as Picker from '../../../src/primitives';

import modules from './picker.module.css';
import { Shell } from './shell';

import '../../integrations/tailwind.css';
import './picker.css';

const meta = {
  title: 'Recipes/Examples/X composer',
  tags: ['recipe'],
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;

/** Plain CSS: picker.css, applied with className. */
export const CSS = () => <Shell className="x-picker" />;

/** CSS Modules: picker.module.css. */
export const CSSModules = () => <Shell className={modules.picker} />;

/** Emotion: styled() over the picker root. */
const EmotionRoot = styledEmotion(Picker.Root)`
  --epr-bg-color: #000000;
  --epr-text-color: #e7e9ea;
  --epr-highlight-color: #1d9bf0;
  --epr-hover-bg-color: rgb(29 155 240 / 10%);
  --epr-focus-bg-color: rgb(29 155 240 / 18%);
  --epr-search-input-bg-color: #000000;
  --epr-search-input-bg-color-active: #000000;
  --epr-search-border-color: #2f3336;
  --epr-search-border-color-active: #1d9bf0;
  --epr-search-input-height: 40px;
  --epr-search-input-border-radius: 9999px;
  --epr-search-input-padding: 0 16px 0 40px;
  --epr-search-input-text-color: #e7e9ea;
  --epr-search-input-placeholder-color: #71767b;
  --epr-category-label-bg-color: rgb(0 0 0 / 85%);
  --epr-category-label-text-color: #e7e9ea;
  --epr-category-label-height: 36px;
  --epr-category-icon-active-color: #1d9bf0;
  --epr-category-icon-inactive-color: #71767b;
  --epr-category-navigation-button-size: 22px;
  --epr-skin-tone-picker-menu-color: rgb(0 0 0 / 90%);
  --epr-emoji-variation-picker-bg-color: #16181c;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 14px;
  width: 360px;
  height: 420px;
  border-radius: 16px;
  background: #000;
  box-shadow: rgb(255 255 255 / 20%) 0 0 15px, rgb(255 255 255 / 15%) 0 0 3px 1px;
  font-family: 'TwitterChirp', -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #2f3336;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 12px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 13px 0 -10px #1d9bf0;
  }

  & [data-epr-part='category-label'] {
    font-size: 17px;
    font-weight: 800;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }
`;

export const Emotion = () => <Shell Root={EmotionRoot} />;

/** styled-components: styled() over the picker root. */
const StyledComponentsRoot = styledComponents(Picker.Root)`
  --epr-bg-color: #000000;
  --epr-text-color: #e7e9ea;
  --epr-highlight-color: #1d9bf0;
  --epr-hover-bg-color: rgb(29 155 240 / 10%);
  --epr-focus-bg-color: rgb(29 155 240 / 18%);
  --epr-search-input-bg-color: #000000;
  --epr-search-input-bg-color-active: #000000;
  --epr-search-border-color: #2f3336;
  --epr-search-border-color-active: #1d9bf0;
  --epr-search-input-height: 40px;
  --epr-search-input-border-radius: 9999px;
  --epr-search-input-padding: 0 16px 0 40px;
  --epr-search-input-text-color: #e7e9ea;
  --epr-search-input-placeholder-color: #71767b;
  --epr-category-label-bg-color: rgb(0 0 0 / 85%);
  --epr-category-label-text-color: #e7e9ea;
  --epr-category-label-height: 36px;
  --epr-category-icon-active-color: #1d9bf0;
  --epr-category-icon-inactive-color: #71767b;
  --epr-category-navigation-button-size: 22px;
  --epr-skin-tone-picker-menu-color: rgb(0 0 0 / 90%);
  --epr-emoji-variation-picker-bg-color: #16181c;
  --epr-emoji-size: 28px;
  --epr-emoji-padding: 5px;
  --epr-horizontal-padding: 14px;
  width: 360px;
  height: 420px;
  border-radius: 16px;
  background: #000;
  box-shadow: rgb(255 255 255 / 20%) 0 0 15px, rgb(255 255 255 / 15%) 0 0 3px 1px;
  font-family: 'TwitterChirp', -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;

  & [data-epr-part='category-nav'] {
    border-bottom: 1px solid #2f3336;
  }

  & [data-epr-part='category-nav'] > * {
    padding: 8px 12px;
  }

  & [data-epr-part='category-tab'][aria-selected='true'] {
    box-shadow: 0 13px 0 -10px #1d9bf0;
  }

  & [data-epr-part='category-label'] {
    font-size: 17px;
    font-weight: 800;
    text-transform: none;
  }

  & [data-epr-part='emoji'] {
    border-radius: 50%;
  }
`;

export const StyledComponents = () => <Shell Root={StyledComponentsRoot} />;

/** MUI: styled() with object styles (plug in theme values as needed). */
const MuiRoot = styledMui(Picker.Root)({
  "--epr-bg-color": "#000000",
  "--epr-text-color": "#e7e9ea",
  "--epr-highlight-color": "#1d9bf0",
  "--epr-hover-bg-color": "rgb(29 155 240 / 10%)",
  "--epr-focus-bg-color": "rgb(29 155 240 / 18%)",
  "--epr-search-input-bg-color": "#000000",
  "--epr-search-input-bg-color-active": "#000000",
  "--epr-search-border-color": "#2f3336",
  "--epr-search-border-color-active": "#1d9bf0",
  "--epr-search-input-height": "40px",
  "--epr-search-input-border-radius": "9999px",
  "--epr-search-input-padding": "0 16px 0 40px",
  "--epr-search-input-text-color": "#e7e9ea",
  "--epr-search-input-placeholder-color": "#71767b",
  "--epr-category-label-bg-color": "rgb(0 0 0 / 85%)",
  "--epr-category-label-text-color": "#e7e9ea",
  "--epr-category-label-height": "36px",
  "--epr-category-icon-active-color": "#1d9bf0",
  "--epr-category-icon-inactive-color": "#71767b",
  "--epr-category-navigation-button-size": "22px",
  "--epr-skin-tone-picker-menu-color": "rgb(0 0 0 / 90%)",
  "--epr-emoji-variation-picker-bg-color": "#16181c",
  "--epr-emoji-size": "28px",
  "--epr-emoji-padding": "5px",
  "--epr-horizontal-padding": "14px",
  width: "360px",
  height: "420px",
  borderRadius: "16px",
  background: "#000",
  boxShadow: "rgb(255 255 255 / 20%) 0 0 15px, rgb(255 255 255 / 15%) 0 0 3px 1px",
  fontFamily: "'TwitterChirp', -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  "& [data-epr-part='category-nav']": {
    borderBottom: "1px solid #2f3336",
  },
  "& [data-epr-part='category-nav'] > *": {
    padding: "8px 12px",
  },
  "& [data-epr-part='category-tab'][aria-selected='true']": {
    boxShadow: "0 13px 0 -10px #1d9bf0",
  },
  "& [data-epr-part='category-label']": {
    fontSize: "17px",
    fontWeight: "800",
    textTransform: "none",
  },
  "& [data-epr-part='emoji']": {
    borderRadius: "50%",
  },
});

export const MUI = () => <Shell Root={MuiRoot} />;

/**
 * Tailwind v4: arbitrary properties for tokens, arbitrary variants for
 * parts. cssLayer="epr" puts the picker's CSS in a cascade layer declared
 * before Tailwind's (`@layer epr, theme, base, components, utilities;`),
 * so utilities override it.
 */
const LayeredRoot = (props: React.ComponentProps<typeof Picker.Root>) => (
  <Picker.Root cssLayer="epr" {...props} />
);

const tailwind = [
  '[--epr-bg-color:#000000]',
  '[--epr-text-color:#e7e9ea]',
  '[--epr-highlight-color:#1d9bf0]',
  '[--epr-hover-bg-color:rgb(29_155_240_/_10%)]',
  '[--epr-focus-bg-color:rgb(29_155_240_/_18%)]',
  '[--epr-search-input-bg-color:#000000]',
  '[--epr-search-input-bg-color-active:#000000]',
  '[--epr-search-border-color:#2f3336]',
  '[--epr-search-border-color-active:#1d9bf0]',
  '[--epr-search-input-height:40px]',
  '[--epr-search-input-border-radius:9999px]',
  '[--epr-search-input-padding:0_16px_0_40px]',
  '[--epr-search-input-text-color:#e7e9ea]',
  '[--epr-search-input-placeholder-color:#71767b]',
  '[--epr-category-label-bg-color:rgb(0_0_0_/_85%)]',
  '[--epr-category-label-text-color:#e7e9ea]',
  '[--epr-category-label-height:36px]',
  '[--epr-category-icon-active-color:#1d9bf0]',
  '[--epr-category-icon-inactive-color:#71767b]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-skin-tone-picker-menu-color:rgb(0_0_0_/_90%)]',
  '[--epr-emoji-variation-picker-bg-color:#16181c]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:14px]',
  '[width:360px]',
  '[height:420px]',
  '[border-radius:16px]',
  '[background:#000]',
  '[box-shadow:rgb(255_255_255_/_20%)_0_0_15px,_rgb(255_255_255_/_15%)_0_0_3px_1px]',
  "[font-family:'TwitterChirp',_-apple-system,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]",
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#2f3336]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_12px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_13px_0_-10px_#1d9bf0]',
  '[&_[data-epr-part=category-label]]:[font-size:17px]',
  '[&_[data-epr-part=category-label]]:[font-weight:800]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
].join(' ');

export const Tailwind = () => <Shell Root={LayeredRoot} className={tailwind} />;

/**
 * shadcn/ui: the brand palette lives in shadcn's theme variables (your
 * globals.css); the picker classes consume them, so it follows the theme.
 */
const shadcnTheme = {
  "--popover": "#000000",
  "--muted-foreground": "#e7e9ea",
  "--primary": "#1d9bf0",
  "--accent": "rgb(29 155 240 / 10%)",
  "--input": "#2f3336",
  "--ring": "#1d9bf0",
  "--popover-foreground": "#e7e9ea"
} as React.CSSProperties;

const shadcn = [
  '[--epr-bg-color:var(--popover)]',
  '[--epr-text-color:var(--muted-foreground)]',
  '[--epr-highlight-color:var(--primary)]',
  '[--epr-hover-bg-color:var(--accent)]',
  '[--epr-focus-bg-color:rgb(29_155_240_/_18%)]',
  '[--epr-search-input-bg-color:#000000]',
  '[--epr-search-input-bg-color-active:#000000]',
  '[--epr-search-border-color:var(--input)]',
  '[--epr-search-border-color-active:var(--ring)]',
  '[--epr-search-input-height:40px]',
  '[--epr-search-input-border-radius:9999px]',
  '[--epr-search-input-padding:0_16px_0_40px]',
  '[--epr-search-input-text-color:var(--popover-foreground)]',
  '[--epr-search-input-placeholder-color:#71767b]',
  '[--epr-category-label-bg-color:rgb(0_0_0_/_85%)]',
  '[--epr-category-label-text-color:#e7e9ea]',
  '[--epr-category-label-height:36px]',
  '[--epr-category-icon-active-color:#1d9bf0]',
  '[--epr-category-icon-inactive-color:#71767b]',
  '[--epr-category-navigation-button-size:22px]',
  '[--epr-skin-tone-picker-menu-color:rgb(0_0_0_/_90%)]',
  '[--epr-emoji-variation-picker-bg-color:#16181c]',
  '[--epr-emoji-size:28px]',
  '[--epr-emoji-padding:5px]',
  '[--epr-horizontal-padding:14px]',
  '[width:360px]',
  '[height:420px]',
  '[border-radius:16px]',
  '[background:#000]',
  '[box-shadow:rgb(255_255_255_/_20%)_0_0_15px,_rgb(255_255_255_/_15%)_0_0_3px_1px]',
  "[font-family:'TwitterChirp',_-apple-system,_'Segoe_UI',_Roboto,_Helvetica,_Arial,_sans-serif]",
  '[&_[data-epr-part=category-nav]]:[border-bottom:1px_solid_#2f3336]',
  '[&_[data-epr-part=category-nav]_>_*]:[padding:8px_12px]',
  '[&_[data-epr-part=category-tab][aria-selected=true]]:[box-shadow:0_13px_0_-10px_#1d9bf0]',
  '[&_[data-epr-part=category-label]]:[font-size:17px]',
  '[&_[data-epr-part=category-label]]:[font-weight:800]',
  '[&_[data-epr-part=category-label]]:[text-transform:none]',
  '[&_[data-epr-part=emoji]]:[border-radius:50%]',
].join(' ');

export const Shadcn = () => (
  // display: contents — the theme scope adds no box.
  <div style={{ display: 'contents', ...shadcnTheme }}>
    <Shell Root={LayeredRoot} className={shadcn} />
  </div>
);
